### ISSUE TITLE
Get  all the items from device  clipboard

### ISSUE THREAD

**Issue by AbdoTareq** [superlistapp/super_native_extensions#111]
How to access all the items on the device clipboard

**Comment by knopp** [comment]
That would be done by quering `platformFormat`s and constructing `SimpleFileFormat` or `SimpleValueFormat` for each of them.

What is your usecase?

**Comment by knopp** [comment]
Alternatively you can do `getFormats(Formats.standartFormats)`.

**Comment by AbdoTareq** [comment]
> That would be done by quering `platformFormat`s and constructing `SimpleFileFormat` or `SimpleValueFormat` for each of them.
> 
> What is your usecase?

To make a clipboard manager app
