### ISSUE TITLE
error "DataProviderManager" not found in release mode!

### ISSUE THREAD

**Issue by hichkas9** [superlistapp/super_native_extensions#112]
hi

This package gives the following error in the **release mode** when copying.

 **Native MessageChannel "DataProviderManager" not found** 

I even used the sample project, but I get this error in the **release mode.**

How to fix it?

**Comment by knopp** [comment]
Which platform?

**Comment by knopp** [comment]
Nevermind. This is a proguard issue. Should be relatively straightforward to fix.

**Comment by knopp** [comment]
Please reopen this issue if the problem persists in 0.3.0.
