### ISSUE TITLE
Clarify Android instructions particularly build.gradle

### ISSUE THREAD

**Issue by gisborne** [superlistapp/super_native_extensions#113]
The instructions say:

> NDK version your project expects is specified in build.gradle.
> 
> android {
>     // by default the project uses NDK version from flutter plugin.
>     ndkVersion flutter.ndkVersion

but my freshly created Android project has no android entry in build.gradle. Do I add this section? Something else?

**Comment by knopp** [comment]
Have you looked in `android/app/build.gradle`? (there are two `build.gradle` files)

**Comment by gisborne** [comment]
Maybe clarify that in the instructions?

Thanks!

**Comment by knopp** [comment]
Should be fixed by https://github.com/superlistapp/super_native_extensions/pulls.
