### ISSUE TITLE
Pasting from Snipping Tool

### ISSUE THREAD

**Issue by adil192** [superlistapp/super_native_extensions#116]
## Description
Following on from #86, I'm encountering another bug on Windows where if you paste an image taken with the snipping tool, the result is just an empty array.
(I can confirm that #86 is fixed and actual files can be pasted as expected.)

## To reproduce
- Open Snipping Tool (e.g. with keyboard shortcut `Shift + Windows + S`)
- Select an area to screenshot, such as something like this
  <img src="https://user-images.githubusercontent.com/21128619/229408299-f304e23b-fe64-46bc-840d-195958f82cab.png" width=200>
- Paste into flutter app
- With the following code snippet, observe that `flutter: pasted []` is printed

## Code snippet

```dart
/// Maps image formats to their file extension.
const Map<SimpleFileFormat, String> formats = {
  Formats.png: '.png',
  // ...
};

for (SimpleFileFormat format in formats.keys) {
  if (!reader.canProvide(format)) continue;
  final progress = reader.getFile(
    format,
    (file) async {
      final stream = file.getStream();
      final List<int> bytes = [];
      await Future.delayed(const Duration(milliseconds: 100));
      await for (final chunk in stream) {
        bytes.addAll(chunk);
        await Future.delayed(const Duration(milliseconds: 100));
      }
      print('pasted $bytes'); // flutter: pasted []

      String extension;
      if (file.fileName != null) {
        extension = file.fileName!.substring(file.fileName!.lastIndexOf('.'));
      } else {
        extension = formats[format]!;
      }

      photoInfos.add(PhotoInfo(
        bytes: Uint8List.fromList(bytes),
        extension: extension,
      ));
    },
  );
  if (progress != null) progresses.add(progress);
}
```
- I added in some `Future.delayed`s to make sure that it wasn't a problem of not waiting long enough. I also increased them to 3000ms but that didn't change anything.

## More info

- Windows 11 22H2 x64
- Flutter 3.7.9
- super_clipboard 0.3.0+1
- super_native_extensions 0.3.0+1
- PR in my repo: https://github.com/adil192/saber/pull/474

```
Flutter 3.7.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 62bd79521d (3 days ago) • 2023-03-30 10:59:36 -0700
Engine • revision ec975089ac
Tools • Dart 2.19.6 • DevTools 2.20.1
```

**Comment by knopp** [comment]
Thank you for the report. This is an oversight in reader implementation. OLE streams need to be rewound before reading and the reader didn't do that. 

The delay when reading should not be necessary.

**Comment by knopp** [comment]
Please reopen if this happens with `0.3.0+2`.

**Comment by adil192** [comment]
Works perfectly :) Thank you!
