### ISSUE TITLE
[super_clipboard][Web] How to copy an image using `Finder` and pasting it using super_clipboard?

### ISSUE THREAD

**Issue by adar2378** [superlistapp/super_native_extensions#118]
Hi, thanks for the great package. I want to copy an image from `Finder` and paste it using `super_clipboard` via CTRL + V command. But when I do that it always just returns the name of the file in `text/plain` format, not the image. With the example app provided in super_clipboard also the same issue. Am I missing something?

**Comment by knopp** [comment]
This is a browser clipboard limitation, and unfortunately not something `super_clipboard` can do anything about. Same thing works as expected in native macOS app for example.

**Comment by adar2378** [comment]
@knopp Thank you for your reply. It will be great if you could provide some documentation regarding this limitation.
