### ISSUE TITLE
Error copying from clipboard on ios devices

### ISSUE THREAD

**Issue by AcarFurkan** [superlistapp/super_native_extensions#119]
I copy the product link from the application named n11 and try to paste it in the textfield, but it gives an error. When I try to get the same link from the clipboard, it prints as blank, but if I go to whatsapp and paste it, I can paste it.
n11 app link:https://www.n11.com

you can see in the video 
https://user-images.githubusercontent.com/65075121/230012390-77c20cde-c309-4719-843d-abb2cf344696.mp4

console does not print anything
![WhatsApp Image 2023-04-05 at 10 26 55 AM](https://user-images.githubusercontent.com/65075121/230012403-953c187c-2a9a-4fa1-bc69-3d0b332091de.jpeg)

**Comment by knopp** [comment]
How exactly is this related to `super_clipboard`? The code you have posted (btw. please don't post code as screenshots) doesn't seem to use `super_clipboard`.

**Comment by AcarFurkan** [comment]
so sorry l was so sleepy l sent the wrong image.
I also execute this code. and it prints null. 
final reader = await ClipboardReader.readClipboard();

    if (reader.canProvide(Formats.plainText)) {
        final text = await reader.readValue(Formats.plainText);
        print(text);
    }

**Comment by knopp** [comment]
Did you try running the app from XCode? Is there any message in the console? This could happen for example when user rejects the paste permission dialog.
