### ISSUE TITLE
Are there someway to get the drag path when using super_drag_and_drop?

### ISSUE THREAD

**Issue by konicyQWQ** [superlistapp/super_native_extensions#121]
```dart
child: DragItemWidget(
  dragItemProvider: (request) async {
    final item = DragItem();
    item.add(....);
    final url = "..."; // can I get the target native path?
    toast("Download file into path $url")
    return item;
  },
  allowedOperations: () => [DropOperation.copy],
  child: DraggableWidget()
)
```

I want to show a toast as below, but it seems that I can not get the drag target native path. Are there someway to get it?

**Comment by knopp** [comment]
There is no such thing as drag target path. The drop target doesn't need to be a file system location. The target application may choose whatever it wants with the file (i.e. just open it, or upload it, etc).

**Comment by knopp** [comment]
If there is a full path you can get it through `getValue(Formats.fileUri)`. But that's only available on desktop and only if is is not a virtual file.

**Comment by Feichtmeier** [comment]
> If there is a full path you can get it through `getValue(Formats.fileUri)`. But that's only available on desktop and only if is is not a virtual file.

Thank you that worked! 👍 
Yes, it is for [a desktop app ](https://github.com/ubuntu-flutter-community/musicpod)
