### ISSUE TITLE
cargo not found: run_rust_tool.cmd finished with non-zero exit value 1

### ISSUE THREAD

**Issue by thinhpq0112** [superlistapp/super_native_extensions#128]
I've install rust:

>cargo --version
cargo 1.69.0 (6e9a83356 2023-04-12)

>rustc --version
rustc 1.69.0 (84c898d65 2023-04-16)

android {
    compileSdkVersion 33
    ndkVersion "25.2.9519653"
    ...

But when I build the project, I faced the issue, even I had invalidated cache and restarted Android Studio: 

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
INFO: Could not find files for the given pattern(s).

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\ThinhDev\AppData\Local\Pub\Cache\hosted\pub.dev\super_native_extensions-0.3.0+2\cargokit\gradle\plugin.gradle' line: 57

* What went wrong:
Execution failed for task ':super_native_extensions:cargokitCargoBuildSuper_native_extensionsDebug'.
Process 'command 'C:\Users\ThinhDev\AppData\Local\Pub\Cache\hosted\pub.dev\super_native_extensions-0.3.0+2\cargokit\gradle\..\run_rust_tool.cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s

cargo not found!

Maybe you need to install Rust? It only takes a minute:

https://www.rust-lang.org/tools/install

Exception: Gradle task assembleDebug failed with exit code 1

**Comment by knopp** [comment]
How did you install rust? Where is it installed? The tool assumes that rust is installed inside `%HOME%\.cargo\bin`, where the standard rust installer puts it.

**Comment by thinhpq0112** [comment]
> How did you install rust? Where is it installed? The tool assumes that rust is installed inside `%HOME%\.cargo\bin`, where the standard rust installer puts it.

I just download from the link above and click to install it, then rust located in %HOME%\.cargo\bin

**Comment by thinhpq0112** [comment]
Oh, I've just restarted Android Studio again and it's now working, yesterday I did many time. Now this issue is done, thank you so much.

**Comment by zoli** [comment]
Isn't better to enable environmental variable pointing to cargo binary path?

**Comment by knopp** [comment]
> Isn't better to enable environmental variable pointing to cargo binary path?

Can you be more specific? What's the use-case here?

**Comment by zoli** [comment]
> > Isn't better to enable environmental variable pointing to cargo binary path?
> 
> Can you be more specific? What's the use-case here?

My case was a bit different from this issue, But I to had rustup installed (my OS is Arch Linux) but I was getting build failure. Because it couldn't find "cargo" in "\~/.cargo/bin/" it was in "/usr/bin/cargo". For fixing the build failure I had to make a symlink from "/usr/bin/cargo" to "~/.cargo/bin/cargo".

What I'm saying is, isn't better to check the given environment path for finding the cargo binary?

**Comment by knopp** [comment]
How did you install rustup? The official rustup installer should put cargo in ~/.cargo. The problem using any cargo that we found is that it might not have access to rustup toolchains.

**Comment by zoli** [comment]
> How did you install rustup? 

With the official Arch Linux package manager Pacman. [This](https://archlinux.org/packages/extra/x86_64/rustup/) is the package and I checked again it puts cargo in "/usr/bin".

**Comment by zoli** [comment]
> Can you for example install additional rust targets without being root when installed like this?

Yes just ran `rustup target add x86_64-unknown-uefi` without problem.

> I also think that we maybe not invoke cargo directly but rather through rustup (i.e. rustup run stable cargo build).

Seems a good idea.

**Comment by knopp** [comment]
I see. With `rustup` the `/usr/bin/cargo` simply links to `/usr/bin/rustup`, which looks for the installed toolchains in user folder. I added issue for this here:

https://github.com/irondash/cargokit/issues/6

**Comment by knopp** [comment]
I just published 0.6.2, could you try if it works without the symlink?

**Comment by zoli** [comment]
> I just published 0.6.2, could you try if it works without the symlink?

Yep. Thanks.
