### ISSUE TITLE
[iOS] [super_drag_and_drop] Build Failure: Unknown Argument '-arch arm64' Error in iOS Simulator

### ISSUE THREAD

**Issue by CEOSiyris** [superlistapp/super_native_extensions#166]
## Environment
- Flutter version: 3.10.6
- Flutter channel: Stable
- Dart version: 3.0.6
- super_drag_and_drop version: v0.5.0
- Operating system: macOS 13.5 (M2 - Silicone)
- Xcode version: Xcode 15 - Beta 4
- Simulator/Device: Any iPhone Simulator (Note: Physical devices are working fine)
- iOS Version: 16.4 & 17.0

## Description
After rerunning the app in the iPhone 14 Pro Max simulator, I encountered an unknown argument error `-arch arm64` that causes the build to fail. The issue persisted even after reverting all code to the last known working state.

Notably, the error seems to point to a failure in running a custom build command for `oslog v0.2.0`. As a workaround, removing the `super_native_extensions` package allows the app to build successfully.

I'm currently on the latest stable version of Flutter but have also tried the beta channel. Both branches of the `super_native_extensions` package were tested with no success in resolving the issue.

## Steps to Reproduce
1. Add super_drag_and_drop to pub spec.yaml
2. Run the app on iPhone Simulator

## Error Output
```
Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
main.dart:1
Xcode build done. 10.0s
Failed to build iOS app
Error (Xcode): unknown argument: '-arch arm64'

Error (Xcode): failed to run custom build command for oslog v0.2.0

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.
Exited
```

## Attempted Solutions
- Reverted all code to last working state
- Switched to the beta version of Flutter
- Tested both branches of `super_native_extensions`
- Removed `super_native_extensions` package (successful build but not a viable solution)

Any insights or solutions to resolve this issue would be greatly appreciated. Thank you!

**Comment by CEOSiyris** [comment]
Turns out using Xcode 14 also works. So that is definitely a viable solution for now but I am very curious why it was previously working fine in Xcode 15.

**Comment by knopp** [comment]
Can you provide verbose build logs?

**Comment by knopp** [comment]
Fixed in cc-rs via https://github.com/rust-lang/cc-rs/pull/759
