### ISSUE TITLE
flutter web, ios, release build

### ISSUE THREAD

**Issue by zezo357** [superlistapp/super_native_extensions#173]
using this logic 

```dart
void copyAttestationImage(IssuedAttestationModel issuedAttestation) async {
  try {
    String requestUrl = issuedAttestation.makeEncodedLink();
    String data = await generateHtmlWithImageAndLink(requestUrl);
    await copyToClipboardHelper(text: requestUrl, html: data);

    showCustomToast(message: "Attestation copied");
  } catch (e, stack) {
    showCustomToast(message: "Failed to copy: $e, stack $stack");
  }
}

void copyAttestationEmbed(IssuedAttestationModel issuedAttestation) async {
  try {
    String requestUrl = issuedAttestation.makeEncodedLink();
    String data = await generateHtmlWithImageAndLink(requestUrl);
    await copyToClipboardHelper(text: data, html: data);

    showCustomToast(message: "Attestation copied");
  } catch (e, stack) {
    showCustomToast(message: "Failed to copy: $e, stack $stack");
  }
}

Future<String> generateHtmlWithImageAndLink(String hyperlink,
    {String host = "https://**.***.***", bool base64Image = true}) async {
  String imgFromAssets = "assets/verify.png";
  if (base64Image) {
    ByteData bytes = await rootBundle.load(imgFromAssets);
    String base64Image = base64.encode(bytes.buffer.asUint8List());
    return '''
    <a href="$hyperlink" style="text-decoration:none;">
      <img src="data:image/png;base64,$base64Image">
    </a>
  ''';
  }
  String endpointUrl = host;

  if (kDebugMode) {
    endpointUrl = "${Uri.base.host}:${Uri.base.port}";
  }

  return '''
    <a href="$hyperlink" style="text-decoration:none;">
      <img src="$endpointUrl$imgFromAssets">
    </a>
  ''';
}

Future<void> copyToClipboardHelper({
  String? html,
  String? text,
  Uint8List? imageData,
}) async {
  final item = DataWriterItem();

  if (html != null) {
    item.add(Formats.htmlText(html));
  }

  if (text != null) {
    item.add(Formats.plainText(text));
  }

  if (imageData != null) {
    item.add(Formats.png(imageData));
  }

  await ClipboardWriter.instance.write([item]);
}


```
works locally(debug) on all platforms

on the locally and deployed (release build) it fails to work on ios (iphone)

with this error
```
Failed to copy: NotAllowedError: The request is
not allowed by the user agent or the platform in
the current context, possibly because the user
denied permission. 
```
stack is empty.

**Comment by knopp** [comment]
Are you testing this with with a https URL?

**Comment by zezo357** [comment]
for context this only happens if copying html, if its only text this doesnt happen

**Comment by knopp** [comment]
This should be addressed with clipboard events.

**Comment by zezo357** [comment]
> This should be addressed with clipboard events.

Can you elaborate more on how to figure it out?

**Comment by knopp** [comment]
Super_clipboard 0.8.0 now support clipboard events on web

https://github.com/superlistapp/super_native_extensions/tree/main/super_clipboard#accessing-clipboard-on-web

Instead of writing to clipboard through async clipboard API, you can register a handler that is invoked every time user presses CTRL+C (or CMD+C) and write to clipboard within the handler. 

On the other hand, I'm not entirely sure if this is going to help on iOS.

**Comment by zezo357** [comment]
> Super_clipboard 0.8.0 now support clipboard events on web
> 
> https://github.com/superlistapp/super_native_extensions/tree/main/super_clipboard#accessing-clipboard-on-web
> 
> Instead of writing to clipboard through async clipboard API, you can register a handler that is invoked every time user presses CTRL+C (or CMD+C) and write to clipboard within the handler. 
> 
> On the other hand, I'm not entirely sure if this is going to help on iOS.

I don't know if that will help or not , will check it again, and open issue if I found it again
