### ISSUE TITLE
How to close context menu when tapping on blur area or outside of menu items?

### ISSUE THREAD

**Issue by MBabken** [superlistapp/super_native_extensions#186]
I'm running the package on android and I found that tapping outside of menu items it's not closing the context menu immediately.
for example when I tap several times very fast sometimes it's closing the context menu.

Also it will be great to have some callbacks for example when context menu is closed and opened.

**Comment by knopp** [comment]
You get a `MenuRequest` argument in the callback that creates the menu. In the request there is `onShowMenu` and `onHideMenu` listenable where you can register the callbacks.

```dart
class MenuRequest {
  /// Invoked when menu is shown.
  final Listenable onShowMenu;

  /// Invoked when menu is hidden. This is will also be invoked when menu
  /// is dismissed before it is shown.
  final ValueListenable<MenuResult?> onHideMenu;

  /// iOS / Android only. Invoked when user taps on menu preview.
  final Listenable onPreviewAction;

  /// Menu location in global coordinates.
  final Offset location;

  MenuRequest({
    required this.onShowMenu,
    required this.onHideMenu,
    required this.onPreviewAction,
    required this.location,
  });
}

typedef MenuProvider = FutureOr<Menu?> Function(MenuRequest request);
```

I can't really reproduce the problem with menu not closing though. Does this happen for you even with the examples from super_context_menu?

**Comment by MBabken** [comment]
yes you are right, I found it later, sorry

**Comment by knopp** [comment]
This issue is stale. Please reopen if you can reproduce the problem with 0.8.0.
