### ISSUE TITLE
How to get destination path when using drag_and_drop plugin?

### ISSUE THREAD

**Issue by guchengxi1994** [superlistapp/super_native_extensions#187]
I was using `drag_and_drop` plugin to download minio files, I could download files successfully, but I could not get the destination directory path. For example, I drag a virtual file from my application to "c:/xxx/xxx/", it can be downloaded to the folder, but I cannot get the path via this plugin. Did I miss something?

**Comment by knopp** [comment]
You can't get the destination directory. There might not even be one. The receiving application is free to do whatever it wants with the stream. It doesn't need to write it to a directory, it may for example upload it immediately.

**Comment by guchengxi1994** [comment]
@knopp I see, thanks for reply.
