### ISSUE TITLE
[macOS] The position of the SVG image in the menu is slightly off-center.

### ISSUE THREAD

**Issue by YeungKC** [superlistapp/super_native_extensions#195]
<img width="243" alt="image" src="https://github.com/superlistapp/super_native_extensions/assets/11473691/f4b1da61-517d-4b02-8662-1bbf27550b9b">

code:

```dart

MenuAction(
                    title: 'with svg',
                    image: MenuImage.withImage((theme, devicePixelRatio) async {
                      final size = theme.size!;
                      final color = theme.color!;

                      const rawSvg =
                          '''<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><rect height="24" width="24" fill="currentColor"/></svg>''';

                      final PictureInfo pictureInfo = await vg.loadPicture(
                          SvgStringLoader(
                            rawSvg,
                            theme: SvgTheme(
                              fontSize: size,
                              currentColor: color,
                            ),
                          ),
                          null);

                      final image = pictureInfo.picture.toImage(
                        (size * devicePixelRatio).round(),
                        (size * devicePixelRatio).round(),
                      );

                      pictureInfo.picture.dispose();
                      return image;
                    }),
                    callback: () {})

```

**Comment by knopp** [comment]
This happens because the SVG is rendered to 24x24 pixels and then you call `picture.toImage(32, 32)`, which does not stretch the image, but it pads it with empty data.

You need some other way to render the SVG for target resolution (32x32 pixels in this case).

**Comment by YeungKC** [comment]
> This happens because the SVG is rendered to 24x24 pixels and then you call `picture.toImage(32, 32)`, which does not stretch the image, but it pads it with empty data.↳
> 
> You need some other way to render the SVG for target resolution (32x32 pixels in this case).↳

I understand what you mean, but I'm a little unsure how to do it. Do you know how to correctly set different sizes of SVGs to a menu image?
