### ISSUE TITLE
Supporting the Dragging of multiple items?

### ISSUE THREAD

**Issue by hobleyd** [superlistapp/super_native_extensions#200]
All,

Are there any plans to support dragging multiple items? Or have I missed some functionality?

I can Drag a single Draggable easily enough, but I am working on a file manager and it would be good to be able to select multiple files and add several things to the DragItem rather than just a single one.

Am I thinking about this weirdly?

Cheers,
David

**Comment by knopp** [comment]
Hey,

dragging multiple items is supported, though it probably needs more documentation. Please see the example here:

(it is a bit outdated some of the method signatures have changed but the concept remains)

https://github.com/superlistapp/super_native_extensions/issues/37#issuecomment-1370150690

By default `DraggableWidget` references `DragItemWidget` found in parent build context, but you can override this and return multiple `DragItemWidgets`, for example based on your selection.

**Comment by hobleyd** [comment]
Awesome, thanks. I would never have figured that out myself.
