### ISSUE TITLE
Running `flutter run -d windows` doesn't work

### ISSUE THREAD

**Issue by coruscant187** [superlistapp/super_native_extensions#208]
When running the example project from `https://github.com/superlistapp/super_native_extensions/tree/main/super_drag_and_drop/example` with `flutter run -d windows`, files can not be dragged over from the explorer to the application.

But when running the EXE from `flutter build windows` directly, it works as intended.

https://github.com/superlistapp/super_native_extensions/assets/67712335/d80b7b35-351f-41b8-ba3c-f98aa0555eee

**Comment by knopp** [comment]
This usually happens when applications are running with different privilege levels. Are you running the command prompt as administrator?

**Comment by coruscant187** [comment]
Yes, I do

**Comment by knopp** [comment]
Is there a reason why? It doesn't seem like a good idea. In any case, drag & drop not working in Windows in this case is by design and there's nothing super_native_extensions can do about it. You can only drag & drop between applications running with same privilege level.
