### ISSUE TITLE
Error when try to get value other than text from Clipboard

### ISSUE THREAD

**Issue by Abdelazziz** [superlistapp/super_native_extensions#21]
On web when i try to get value from ClipBoard other than text like image or file i get this error 
`Error: DataError: No valid data on clipboard.`
I am using this code :
`final reader = await ClipboardReader.readClipboard()`
plugin https://pub.dev/packages/super_clipboard
Please tell what to do or what i am missing to get a file or image from ClipBoard.

**Comment by knopp** [comment]
Are you by any chance using Firefox? Not all browsers support reading images from Clipboard.

**Comment by Abdelazziz** [comment]
Hi
Now i am using google chrom the last version, and i think this error it seem to be only when i copied a file or image, because when i tried to past a text there no error, and i am able to get text from clipboard.
