### ISSUE TITLE
Why this package has not support for flutter web?

### ISSUE THREAD

**Issue by abdulrehman192** [superlistapp/super_native_extensions#210]
There should be support for flutter web.

**Comment by knopp** [comment]
There is support for flutter web. What are you missing exactly?

**Comment by abdulrehman192** [comment]
When I used this package code in flutter web nothing happens and when I run
code on Android then build failed. I already installed the rust.

**Comment by knopp** [comment]
You need to be more specific here. I can't really help you without knowing the actual build error. Or what does it mean "nothing happens".

Btw. If you use the [0.7.0-dev.6](https://pub.dev/packages/super_drag_and_drop/versions/0.7.0-dev.6) version it does not require Rust installed anymore.

**Comment by abdulrehman192** [comment]
This is the error when run on android
Launching lib\MenuScreen.dart on AC2003 in debug mode...
Running Gradle task 'assembleDebug'...
Parameter format not correct -
Note: C:\Users\mrabd\AppData\Local\Pub\Cache\hosted\pub.dev\super_native_extensions-0.7.0-dev.6\android\src\main\java\com\superlist\super_native_extensions\DragDropHelper.java
uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the file specified.
The system cannot find the file specified.
Cannot operate on packages inside the cache.
Compiling bin/build_tool_runner.dart to kernel file
bin/build_tool_runner.dill.
Info: Compiling with sound null safety.
Error: Couldn't resolve the package 'build_tool' in
'package:build_tool/build_tool.dart'.
bin/build_tool_runner.dart:1:8: Error: Not found:
'package:build_tool/build_tool.dart'
import 'package:build_tool/build_tool.dart' as build_tool;
       ^
bin/build_tool_runner.dart:3:15: Error: Method not found: 'runMain'.
   build_tool.runMain(args);
              ^^^^^^^
Could not find a command named "bin\build_tool_runner.dill".

Usage: dart <command|dart-file> [arguments]

Global options:
-v, --verbose               Show additional command output.
    --version               Print the Dart SDK version.
    --enable-analytics      Enable analytics.
    --disable-analytics     Disable analytics.
    --suppress-analytics    Disallow analytics for this `dart *` run
without changing the analytics configuration.
-h, --help                  Print this usage information.

Available commands:
  analyze    Analyze Dart code in a directory.
  compile    Compile Dart to various formats.
  create     Create a new Dart project.
  devtools   Open DevTools (optionally connecting to an existing
application).
  doc        Generate API documentation for Dart projects.
  fix        Apply automated fixes to Dart source code.
  format     Idiomatically format Dart source code.
  info       Show diagnostic information about the installed tooling.
  pub        Work with packages.
  run        Run a Dart program.
  test       Run tests for a project.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\mrabd\AppData\Local\Pub\Cache\hosted\pub.dev\irondash_engine_context-0.4.0-dev.2\cargokit\gradle\plugin.gradle'
line: 59

* What went wrong:
Execution failed for task
':irondash_engine_context:cargokitCargoBuildIrondash_engine_context_nativeDebug'.
> Process 'command 'C:\Users\mrabd\AppData\Local\Pub\Cache\hosted\pub.dev\irondash_engine_context-0.4.0-dev.2\cargokit\gradle\..\run_build_tool.cmd''
finished with non-zero exit value 64

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by abdulrehman192** [comment]
Show the menu successfully on the web, but working on right click only. how
to show on left click or on hover?

**Comment by knopp** [comment]
Context menu is supposed to be opened on right click. What is the use case of showing context menu on hover? Note that feature request for menu buttons is tracked here: https://github.com/superlistapp/super_native_extensions/issues/189

Regarding the build error, this is very suspicious: `Cannot operate on packages inside the cache.`

Which folder is your project located in? Also, can you post here output of flutter doctor? The package that fails to build should be placed in build directory of your project. So the pub error does not make any sense.
