### ISSUE TITLE
Error on write

### ISSUE THREAD

**Issue by seakingii** [superlistapp/super_native_extensions#22]
`
final item = DataWriterItem();
item.add(Formats.png(result));
await ClipboardWriter.instance.write([item]);
`

get error:

PlatformException(super_native_extensions_error, "Windows Error: 尚未调用 CoInitialize。", otherError, null)

**Comment by knopp** [comment]
Replace `CoInitialize` in main.cc with `OleInitialize`. Drag&Drop on windows requires OLE. I think the readme needs to be updated.

**Comment by CroatianHusky** [comment]
I had the same issue, and did the following to fix it:
- Find the `main.cpp` file (`windows/runner/main.cpp` in your project folder)
- find the like with `::CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);`, and change it to `::OleInitialize(nullptr);`

Please correct me if I should have fixed it differently, but this has worked for me.

**Comment by knopp** [comment]
That is the correct solution, however after https://github.com/superlistapp/super_native_extensions/pull/51 it should be no longer needed.
