### ISSUE TITLE
[super_clipboard] JPEG image issues on the Windows desktop platform.

### ISSUE THREAD

**Issue by ltxhhz** [superlistapp/super_native_extensions#222]
Hello👋.
I modified `super_clipboard/example`.

https://github.com/superlistapp/super_native_extensions/blob/5d5f16dca74ce3071fb7847597920019df74f995/super_clipboard/example/lib/main.dart#L260-L269

<details>
<summary>modified</summary>

```dart
Future<Uint8List> createImageData(Color color) async {
  final recorder = ui.PictureRecorder();
  final canvas = Canvas(recorder);
  final paint = Paint()..color = color;
  canvas.drawOval(const Rect.fromLTWH(0, 0, 200, 200), paint);
  final picture = recorder.endRecording();
  final image = await picture.toImage(200, 200);
  final data = await image.toByteData(format: ui.ImageByteFormat.png);
  final img.Image rawImage = img.decodePng(data!.buffer.asUint8List())!;
  return img.encodeJpg(rawImage);
}
```

</details>

I use the [image library](https://pub.dev/packages/image) to convert the image to jpg format.
But this example software still recognizes the image as a png.
![image](https://github.com/superlistapp/super_native_extensions/assets/51697596/a8f62b2e-e255-4438-99e3-eb07f53cac4b)

And when I paste this image into another app the image changes color and seems to be offset.

this is in Dingtalk:
![image](https://github.com/superlistapp/super_native_extensions/assets/51697596/0cad16ae-ef35-4214-8055-59c548ab69e5)

this is in QQ:
![image](https://github.com/superlistapp/super_native_extensions/assets/51697596/39f80ecb-4ccb-4c67-884d-f5231836d431)

But when I use win+v to paste from the clipboard history, the image is normal.
![image](https://github.com/superlistapp/super_native_extensions/assets/51697596/fc315c35-2d99-4f49-b63b-46c31ea6189d)

<details>
<summary>this is my system infomation</summary>

```
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          ltxhhz
Registered Organization:   N/A
Product ID:                00330-80000-00000-AA659
Original Install Date:     2/27/2023, 11:21:10 AM
System Boot Time:          10/20/2023, 12:30:25 PM
System Manufacturer:       LENOVO
System Model:              21J0
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 25 Model 68 Stepping 1 AuthenticAMD ~3201 Mhz
BIOS Version:              LENOVO LECN18WW, 2/28/2023
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             zh-cn;Chinese (China)
Input Locale:              zh-cn;Chinese (China)
Time Zone:                 (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi
Total Physical Memory:     28,357 MB
Available Physical Memory: 8,685 MB
Virtual Memory: Max Size:  41,767 MB
Virtual Memory: Available: 17,431 MB
Virtual Memory: In Use:    24,336 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-BPD572F
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5030651
                           [02]: KB5012170
                           [03]: KB5031354
                           [04]: KB5031592
```

</details>

**Comment by ltxhhz** [comment]
The Gif image seems to only copy the first frame and is also offset when pasted like in the previous screenshot, but the color doesn't change.

**Comment by knopp** [comment]
a) Did you set the correct clipboard format when writing into clipboard?
b) Most window applications only support DIB or DIB v5 format when pasting. Super_clipboard will convert PNG to DIB/DIBv5 on demand, but it doesn't do that for JPEG images.

**Comment by ltxhhz** [comment]
Thanks for the reply.
a) Sorry, I forgot to change the clipboard format.🥲
b) Sorry I know less about this, I just went and looked into DIB/DIBv5, does this mean I need to convert a jpg image to png before copying it, or will you guys support this later?

**Comment by knopp** [comment]
For now I'd suggest converting it to PNG. The conversion is lossless anyway.

**Comment by knopp** [comment]
But can also put the original JPG in clipboard for applications that can handle JPG directly.

**Comment by ltxhhz** [comment]
I got it,thank you.

**Comment by ltxhhz** [comment]
> The Gif image seems to only copy the first frame and is also offset when pasted like in the previous screenshot, but the color doesn't change.

Is that the same reason for this problem?

**Comment by knopp** [comment]
Did you copy the GIF image with correct format? Does the target application supports pasting animated GIFs?

**Comment by ltxhhz** [comment]
You're right, I haven't tried it in other apps before. Thanks again.

**Comment by ltxhhz** [comment]
I just found out.This actually works just fine.

```dart
item.add(Formats.fileUri(value[index].file.uri));
item.add(Formats.htmlText("<img src=\"file://${value[index].file.uri.path}\" />"));
// other image item
```

**Comment by knopp** [comment]
That doesn't really copy the image, just a HTML snippet that references it. What exactly is the use case here? Which applications are you targeting?

**Comment by ltxhhz** [comment]
My target app is a chat type.
I just got the idea by copying the jpg image from the chat software and then viewing it in the example software.
![image](https://github.com/superlistapp/super_native_extensions/assets/51697596/23b7ca12-e175-4231-b981-b54952f0320c)

<details>
<summary>code</summary>

```dart
final item = DataWriterItem();
item.add(Formats.fileUri(value[index].file.uri)); // There was no such line before.
item.add(Formats.htmlText("<img src=\"file://${value[index].file.uri.path}\" />")); // There was no such line before.
switch (lookupMimeType(value[index].file.path)) {
  case 'image/png':
    item.add(Formats.png(value[index].file.readAsBytesSync()));
    break;
  case 'image/jpeg':
    item.add(Formats.jpeg(value[index].file.readAsBytesSync()));
    break;
  case 'image/webp':
    item.add(Formats.webp(value[index].file.readAsBytesSync()));
    break;
  case 'image/bmp':
    item.add(Formats.bmp(value[index].file.readAsBytesSync()));
    break;
  case 'image/gif':
    item.add(Formats.gif(value[index].file.readAsBytesSync()));
    break;
  case 'image/svg+xml':
    item.add(Formats.svg(value[index].file.readAsBytesSync()));
    break;
  default:
  // item.add(Formats.fileUri(value[index].path.uri));
}
ClipboardWriter.instance.write([
  item
]).then((value) {
  showToast('已复制');
});
```

</details>
