### ISSUE TITLE
Flutter Web Release Not Working

### ISSUE THREAD

**Issue by DragonSlayer88** [superlistapp/super_native_extensions#224]
In debug mode it works fine, release mode i get this error:
TypeError: null: type 'minified:DV' is not a subtype of type 'minified:i'
![Untitled](https://github.com/superlistapp/super_native_extensions/assets/20056214/cd3fe260-97c2-4430-9729-80300c0ca9f9)

**Comment by Jesse-Abruzzo** [comment]
Any help with this? Its completely broken on flutter web. I cant copy images or html text in release mode. anyone else experience this issue?

**Comment by knopp** [comment]
Do you get any error message in console? Is it same as the original issue?

**Comment by knopp** [comment]
Btw. Can you run the app with `--profile` instead of `--release` in order to preserve class names?

**Comment by Jesse-Abruzzo** [comment]
The error message is what i posted in the first message. i can try to run in the --profile

**Comment by Jesse-Abruzzo** [comment]
So running it like this: Launching lib\main.dart on Chrome in release mode... and Launching lib\main.dart on Chrome in profile mode...
it seems to work. Its when i build it and host it on iis that it doesnt work. So while hosting it i got the error that you saw in the original post.

**Comment by knopp** [comment]
Are you accessing the page through http or https? Clipboard on non-localhost domains only works with https.

**Comment by Jesse-Abruzzo** [comment]
Ohhh that could be it. Its on http. il try to switch over to https and try it out. thanks! il let you know.

**Comment by llorenzo** [comment]
I have a simelar problem. I use https://

Uncaught : Error: globalThis.ClipboardItem is not a constructor

**Comment by llorenzo** [comment]
You guessed it: Firefoy. It works on Chrome and Safari...

**Comment by knopp** [comment]
Firefox does not support clipboard API unfortunately.

**Comment by knopp** [comment]
Super_clipboard now has support for clipboard events on web, which also work on firefox:

https://github.com/superlistapp/super_native_extensions/tree/main/super_clipboard#accessing-clipboard-on-web
