### ISSUE TITLE
[super_drag_and_drop] drag drop to desktop ,  An indescribable functionality or bug.

### ISSUE THREAD

**Issue by 24** [superlistapp/super_native_extensions#225]
It's very strange. I was able to run the example and successfully drag and drop the Text to the desktop, 
generating a`VirtualFile.txt` file with content inside.
 
However, when I tried running it again,

I couldn't drag and drop anymore.

I guess that it should be possible to drag and drop text or images to the desktop. 
However, there might be a bug that is causing the functionality to fail.

OS System: 13.6 (22G120)
Flutter 3.13.8

**Comment by knopp** [comment]
I'm unable to reproduce this. Does this happen every time you start the application?

**Comment by 24** [comment]
only happened once , so it's very strange
