### ISSUE TITLE
super_native_extensions cant compile in ndk 23

### ISSUE THREAD

**Issue by Jorgegzz** [superlistapp/super_native_extensions#23]
trying to run the project throws `note: ld: error: unable to find library -lgcc`
the current workaround would be changing the target ndk to v22

**Comment by knopp** [comment]
Thanks for the report. We'll need to address this: https://github.com/rust-lang/rust/pull/85806

**Comment by knopp** [comment]
Fixed via https://github.com/superlistapp/super_native_extensions/commit/e75b7c05ec8cecded3941db274a2505b2f48dcee.
