### ISSUE TITLE
Separating Key Up/Down Event Handling

### ISSUE THREAD

**Issue by suysoftware** [superlistapp/super_native_extensions#232]
Hello again Matt - another suggestion that might enhance its functionality: separate handlers for key down and key up events.

**Feature Description:**
Currently, there is no differentiation between key press and release events in the library. We propose the introduction of separate handlers for key down (when the key is first pressed) and key up (when the key is released) events.

**Why this feature is beneficial:**
This change would allow for more complex interactions like triggering different actions on press and release, or implementing features like long press. It would make the library more flexible and capable of handling a wider range of use cases.

We appreciate your work on this project and hope you'll consider our proposal 🙏

**Comment by knopp** [comment]
This seems to be doable on macOS, but may be little bit tricky on windows since `WM_HOTKEY` is only fire on key down. This may require polling for pressed keys.
