### ISSUE TITLE
Can't remove border radius on previewBuilder widget

### ISSUE THREAD

**Issue by Kiruel** [superlistapp/super_native_extensions#235]
Hi, I'm looking a way to change the border radius of the `previewBuilder`.

What I have:

```dart
ContextMenuWidget(
              previewBuilder: (context, child) {
                return Container(
                  color: Colors.blue,
                  height: 100,
                  width: 100,
                );
              },
```

What I get:
<img width="369" alt="Screenshot 2023-11-21 at 17 09 10" src="https://github.com/superlistapp/super_native_extensions/assets/8250175/d3ccddc4-3d35-4a1b-b899-3b3baa791b66">

We can see a border radius, but in my container there no borderRadius. This is a bug or a default radius that I can change ?

**Comment by knopp** [comment]
Which platform is this on?

**Comment by Kiruel** [comment]
iOS platform

**Comment by knopp** [comment]
On iOS the border radius is enforced by the iOS menu system and cannot be adjusted.
