### ISSUE TITLE
How to change the brightness to dark.

### ISSUE THREAD

**Issue by Kiruel** [superlistapp/super_native_extensions#236]
<img width="251" alt="Screenshot 2023-11-24 at 09 59 13" src="https://github.com/superlistapp/super_native_extensions/assets/8250175/c6daef1a-8430-4a1d-9eba-70d11225c2bc">

I want to change the background to dark my theme use `brightness: Brightness.dark` in `CupertinoThemeData`, but the background still light. How I can change that ? 

Thanks,

**Comment by Kiruel** [comment]
This is based on the system theme. So I think only the user can change this. Closing this issue.

**Comment by knopp** [comment]
Indeed. This is a native iOS menu.
