### ISSUE TITLE
[iOS] Cannot drag and drop audio and video files on iOS devices 

### ISSUE THREAD

**Issue by lelandtsc** [superlistapp/super_native_extensions#252]
On iPad, drag and drop audio and video files from 'Files' app will get this error:

flutter: Error reading value PlatformException(super_native_extensions_error, Operation not permitted (os error 1), ioError, null)

However, dragging images, pdf, pptx works without problem. Also no issue observed on Chrome OS and Mac OS.

                           onPerformDrop: (performDropEvent) async {                 
                               final item = performDropEvent.session.items.first;
                                final reader = item.dataReader;

                                if (reader?.canProvide(Formats.mp3) == true) {
                                  final result = <int>[];
                                  reader?.getFile(Formats.mp3, (file) async {        
                                     final stream = file.getStream();
                                     await for (final data in stream) {
                                       for (int i = 0; i < data.length; i++) {
                                         result.add(data[i]);
                                       }
                                     }
                                  }, onError: (error) {
                                    print('Error reading value $error');
                                  });
                                }
                                return;
                              }

Error occurs when getFile() is called.

Flutter version 3.16.2
iPad Air 3rd generation version 17.1.2

**Comment by knopp** [comment]
Unfortunately I don't seem to be able to reproduce this. Does happen to all MP3 files or just some of them?


https://github.com/superlistapp/super_native_extensions/assets/96958/6c1953c4-ac0c-4a94-b1d1-0882022cca34

**Comment by lelandtsc** [comment]
Thank you for responding.

All the audio and video files I use happen to generate the error, including extensions with .mp3, .mov, .mp4...etc.
I hereby provide a mov clip since mp3 and aac are not allowed to add here.

https://github.com/superlistapp/super_native_extensions/assets/49741263/87ca3a1a-bdf0-4667-b7ae-e49506239119

May I ask if you're using a simulator to do the test? And what does the word 'virtual' mean that displays after the file name? Just to want to confirm if you used a different method to get the file instead of 'reader.getFile()'.

**Comment by knopp** [comment]
On some platforms "virtual" means data possibly generated on demand. On iOS it makes no difference. `getFile()` is always used to access the content. I'll retest this on device. But gut feeling is that there is some other factor here that I might be missing.

**Comment by lelandtsc** [comment]
Thanks for the quick reply. 
Alright, got it. I thought getting a virtual file would require using other methods. Thank you for the support, I look forward to hear the good news.

**Comment by lelandtsc** [comment]
Any update on this? Please let me know if you tested it on device.

**Comment by knopp** [comment]
Sorry for the delay. This happened because unlike on Simulator on iOS the application runs in sandbox, and for some reason, accessing *some* of the files requires security scope access.
