### ISSUE TITLE
can't run with super_drag_and_drop launcher configration

### ISSUE THREAD

**Issue by MU-XICHEN** [superlistapp/super_native_extensions#254]
like occuring a type error, list<int> to utf8list

Launching lib\main.dart on Windows in debug mode...
main.dart:1
../../super_clipboard/lib/src/format_conversions.dart(85,15): error G44692867: A value of type 'List<int>' can't be returned from a function with return type 'Uint8List'. [C:\Users\songsongcai\projects\super_native_extensions\super_drag_and_drop\example\build\windows\flutter\flutter_assemble.vcxproj]
format_conversions.dart:1
../../super_clipboard/lib/src/format_conversions.dart(89,15): error G44692867: A value of type 'List<int>' can't be returned from a function with return type 'Uint8List'. [C:\Users\songsongcai\projects\super_native_extensions\super_drag_and_drop\example\build\windows\flutter\flutter_assemble.vcxproj]
format_conversions.dart:1
../../super_clipboard/lib/src/reader_internal.dart(221,45): error GC2F972A8: The argument type 'List<int>' can't be assigned to the parameter type 'Uint8List'. [C:\Users\songsongcai\projects\super_native_extensions\super_drag_and_drop\example\build\windows\flutter\flutter_assemble.vcxproj]
reader_internal.dart:1
../lib/src/drag_internal.dart(157,41): error GC2F972A8: The argument type 'HitTestResult' can't be assigned to the parameter type 'HitTestResult Function()'. [C:\Users\songsongcai\projects\super_native_extensions\super_drag_and_drop\example\build\windows\flutter\flutter_assemble.vcxproj]

**Comment by MU-XICHEN** [comment]
Every example will show above tips when i want to debug this plugin

**Comment by knopp** [comment]
Which Flutter version are you using? You need to be at least on 3.16 (latest stable) to build super_native_extensions.

**Comment by MU-XICHEN** [comment]
> Which Flutter version are you using? You need to be at least on 3.16 (latest stable) to build super_native_extensions.

thanks for answering, i will try
