### ISSUE TITLE
Undefined reference to GLIBC_2.34

### ISSUE THREAD

**Issue by AnsahMohammad** [superlistapp/super_native_extensions#256]
I'm trying to build an app that uses super_native_extensions `super_native_extensions 0.7.0`.
I'm running on Ubuntu LTS 22.04, **my GlibC version is 2.35**

Whenever i try to build the application, it says **undefined reference to GLIBC 2.34** and breaks the build process. I wanted to know how to fix this :

![image](https://github.com/superlistapp/super_native_extensions/assets/85027826/b9841c11-ce4b-4f8e-b747-e514180548ba)

```
[   +8 ms] /snap/flutter/current/usr/bin/ld:
/home/ansah/Documents/Programming/GitWorld/AppFlowy/frontend/appflowy_flutter/build/linux/x64/debug/plugins/super_native_extensions/libsuper_native_extensions.so: undefined
reference to `pthread_setspecific@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld:
/home/ansah/Documents/Programming/GitWorld/AppFlowy/frontend/appflowy_flutter/build/linux/x64/debug/plugins/super_native_extensions/libsuper_native_extensions.so: undefined
reference to `dlopen@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld:
/home/ansah/Documents/Programming/GitWorld/AppFlowy/frontend/appflowy_flutter/build/linux/x64/debug/plugins/super_native_extensions/libsuper_native_extensions.so: undefined
reference to `fstat64@GLIBC_2.33'
[        ] /snap/flutter/current/usr/bin/ld:
/home/ansah/Documents/Programming/GitWorld/AppFlowy/frontend/appflowy_flutter/build/linux/x64/debug/plugins/super_native_extensions/libsuper_native_extensions.so: undefined
reference to `stat64@GLIBC_2.33'
[        ] /snap/flutter/current/usr/bin/ld:
/home/ansah/Documents/Programming/GitWorld/AppFlowy/frontend/appflowy_flutter/build/linux/x64/debug/plugins/super_native_extensions/libsuper_native_extensions.so: undefined
reference to `pthread_getspecific@GLIBC_2.34'
[   +8 ms] /snap/flutter/current/usr/bin/ld:
/home/ansah/Documents/Programming/GitWorld/AppFlowy/frontend/appflowy_flutter/build/linux/x64/debug/plugins/super_native_extensions/libsuper_native_extensions.so: undefined
reference to `pthread_key_delete@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld:
/home/ansah/Documents/Programming/GitWorld/AppFlowy/frontend/appflowy_flutter/build/linux/x64/debug/plugins/super_native_extensions/libsuper_native_extensions.so: undefined
reference to `pthread_key_create@GLIBC_2.34'
[   +5 ms] /snap/flutter/current/usr/bin/ld:
/home/ansah/Documents/Programming/GitWorld/AppFlowy/frontend/appflowy_flutter/build/linux/x64/debug/plugins/super_native_extensions/libsuper_native_extensions.so: undefined
reference to `dlsym@GLIBC_2.34'
[   +5 ms] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[   +2 ms] ninja: build stopped: subcommand failed.
[  +15 ms] Building Linux application... (completed in 7.6s)
[   +1 ms] "flutter linux" took 8,915ms.
[   +6 ms] Build process failed
```

**Comment by knopp** [comment]
I think the problem here is that building with Flutter from snap uses old glibc. Not sure how to solve this. Perhaps using the `Ubuntu 20.04` image when building the binaries or link with zig and cross compile for different libc version.

**Comment by AnsahMohammad** [comment]
@knopp Thanks a lot. The problem was with snap flutter. I reinstalled flutter manually and it worked !

**Comment by jpohhhh** [comment]
I'm seeing this when building a Linux release on CI (Codemagic).
It does seem straightforward, Ubuntu is almost 3 years old, ldd is 2.31. [^1]
From there I'd expect to have to take it up with Codemagic: i.e. they'd need to provide a newer Ubuntu.
I expect that's non-trivial.

To workaround, I'm thinking I'll follow a few things mentioned @ https://github.com/superlistapp/super_native_extensions/issues/214
1. Try installing Flutter latest via checkout the flutter project and add the bin directory to PATH.
2. Try forcing use of precompiled libraries via 0.7.0 and hiding Rust.


[^1]
- Codemagic's Linux image is Ubuntu 20.04.2 LTS (Feb 4 2021)
- `ldd --version`: ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31

**Comment by jpohhhh** [comment]
`rustc` isn't installed. 

I assume that since the prebuilts are from a modern system, they link against a newer glibc than 2.31.

**Comment by jpohhhh** [comment]
I went back to the basics, upgraded from 0.7.3 to 0.8.0 for `super_clipboard` (and thus `super_clipboard
