### ISSUE TITLE
[Super_clipboard] [Web] paste image from devices to web failed

### ISSUE THREAD

**Issue by sherlockvn** [superlistapp/super_native_extensions#258]
- I run the example in super_clipboard package. When i copy image from my Macos devices, then paste to the example program, there is only text/plain is paste.

https://github.com/superlistapp/super_native_extensions/assets/43041967/f03e01cc-ca20-4cf9-83b7-2941401f8863

**Comment by knopp** [comment]
Asynchronous clipboard on web doesn't provide access to files copied to clipboard. Those can only be accessed when handling the 'paste' event.

Latest prerelease version (0.8.0-dev.3) allows hooking into the paste event. You can run the example from current git main and trigger the paste event using cmd+v. the file should show.

**Comment by sherlockvn** [comment]
Thank you for your response. I've conducted tests on the most recent main branch, and while the desktop platform is performing smoothly, I've observed that the web only paste the text/plain with image.

Below is the log that may help you. Thank you for your time

getObject: (-32603) Unexpected DWDS error for getObject: type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1930:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2499:21)
#2      VmService.getObject (package:vm_service/src/vm_service.dart:2231:7)
#3      ProtocolConverter._getterNamesForClassHierarchy (package:dds/src/dap/protocol_converter.dart:728:25)
<asynchronous suspension>
#4      ProtocolConverter.convertVmInstanceToVariablesList (package:dds/src/dap/protocol_converter.dart:299:13)
<asynchronous suspension>
#5      DartDebugAdapter.variablesRequest (package:dds/src/dap/adapters/dart.dart:1972:26)
<asynchronous suspension>
#6      BaseDebugAdapter.handle (package:dds/src/dap/base_debug_adapter.dart:141:7)
<asynchronous suspension>

**Comment by knopp** [comment]
That stacktrace is from debug adapter, it doesn't seem to be in any way related to super_clipboard.

**Comment by sherlockvn** [comment]
Actually, the cmd+V works but paste button not working. Sr 
![treasure_unlock](https://github.com/superlistapp/super_native_extensions/assets/43041967/740cb1f4-af6e-4bef-be55-381b2503158e)

**Comment by knopp** [comment]
That is expected. The only way to trigger paste even in browser is pressing ctrl/cmd + v or through browser menu. Paste button is using the asynchronous clipboard API, which is more limited, requires confirmation and is not enabled at all in firefox.

**Comment by sherlockvn** [comment]
Ah. I see. Thank you for your time.
