### ISSUE TITLE
The argument type 'HitTestResult Function()' can't be assigned to the parameter type 'HitTestResult?'

### ISSUE THREAD

**Issue by darkomenx** [superlistapp/super_native_extensions#260]
**Technical information  :** 
- Windows 11 Pro
- Android Studio Hedgehog 2023.1.1 (Build #AI-231.9392.1.2311.11076708, built on November 9, 2023)
- Flutter 3.16.1
- Dart 3.2.1
- Rust 1.74.1 (a28077b28 2023-12-04)

**Error :** 

```
`Launching lib\main.dart on Windows in debug mode...
Building Windows application...
/C:/Users/toto/AppData/Local/Pub/Cache/hosted/pub.dev/super_drag_and_drop-0.3.0+2/lib/src/drag_internal.dart(146,41): error GC2F972A8: The argument type 'HitTestResult Function()' can't be assigned to the parameter type 'HitTestResult?'. 

[C:\PROJECT\ANDROIDStudio\MyBestProject\build\windows\x64\flutter\flutter_assemble.vcxproj]

C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5): error MSB8066: la build personnalis�e de 'C:\PROJECT\ANDROIDStudio\MyBestProject\build\windows\x64\CMakeFiles\e06ad74d88d57f94f34b2c209e55916f\flutter_windows.dll.rule;

C:\PROJECT\ANDROIDStudio\MyBestProject\build\windows\x64\CMakeFiles\468867c259ba90e51417479bb0316122\flutter_assemble.rule' s'est arr�t�e. Code�1. [C:\PROJECT\ANDROIDStudio\MyBestProject\build\windows\x64\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.`
```

**Context :** 

I want to use the super_drag_and_drop.
I launch : flutter pub add super_drag_and_drop
I launch and install Rust program with the rustup-init.exe provided 
I upgrade Rust with rustup upgrade
I imported package like this : 'import 'package:super_drag_and_drop/super_drag_and_drop.dart';'
I use package like this (basic just for first try) :  

                          DropRegion(
                            formats: Formats.standardFormats,
                            onDropOver: (DropOverEvent)
                            {
                              final item = DropOverEvent.session.items.first;
                              if (item.localData is Map) {
                                // This is a drag within the app and has custom local data set.
                              }
                              if (item.canProvide(Formats.plainText)) {
                                // this item contains plain text.
                              }
                              // This drop region only supports copy operation.
                              if (DropOverEvent.session.allowedOperations.contains(DropOperation.copy)) {
                                return DropOperation.copy;
                              } else {
                                return DropOperation.none;
                              }
                            },
                            onDropEnter: (event) {},
                            onDropLeave: (event) {},
                            onPerformDrop: (PerformDropEvent) async
                            {
                              final item = PerformDropEvent.session.items.first;

                              // data reader is available now
                              final reader = item.dataReader!;

                              if (reader.canProvide(Formats.plainText))
                              {
                                reader.getValue<String>(Formats.plainText, (value) {
                                  if (value != null) {
                                    // You can access values through the `value` property.
                                    print('Dropped text: ${value}');
                                  }
                                }, onError: (error) {
                                  print('Error reading value $error');
                                });
                              }

                              if (reader.canProvide(Formats.png))
                              {
                                reader.getFile(Formats.png, (file) {
                                  final stream = file.getStream();
                                }, onError: (error) {
                                  print('Error reading value $error');
                                });
                              }
                            },
                            child: const Padding(
                              padding: EdgeInsets.all(15.0),
                              child: Text('Drop items here'),
                            ),
                          )

**Questions :** 

- Did I forget something ?
- Did I do something wrong ?
- How can resolve this ?
- Why this error throw ?

Thank you for your help

**Comment by knopp** [comment]
You seem to be using a very old version of super_drag_and_drop (0.3.0). Last version at pub.dev is 0.7.3.

**Comment by darkomenx** [comment]
Thank you for your very speed response.

I use this command for install package : `flutter pub add super_drag_and_drop`
Whereas it installed the old version.

If I force to install 0.7.3 latest version it tell me that exist conflict with 
- device_info_plus package 
- bitsdojo_window

I will investigate around this and return here to keep track

**Comment by knopp** [comment]
Please reopen if this is not resolved.
