### ISSUE TITLE
The menu only appears every other click

### ISSUE THREAD

**Issue by onism0106** [superlistapp/super_native_extensions#263]
When I right-click, the menu appears. After the menu is closed and I click it again, the menu does not appear. When I click it again, the menu appears again.

**Comment by knopp** [comment]
Which platform is this on? And which version?

**Comment by onism0106** [comment]
> Which platform is this on? And which version?

The platform is macOS, using 0.7.3

**Comment by knopp** [comment]
Are you able to reproduce this with the example app?

**Comment by onism0106** [comment]
When I was using ContextMenuWidget, child used GestureDetector because I needed the component to respond to both the right click and onTap, and the above problem occurred, with the menu appearing every other time

**Comment by knopp** [comment]
If your `GestureDetector` was handling the right click event than that could make context menu not work all the time.

**Comment by onism0106** [comment]
My GesutreDetector does not add the onSecondaryTap method, 

The code is as follows:

`return ContextMenuWidget(
                    menuProvider: (_) {
                      return Menu(
                        children: [
                          MenuAction(title: 'Menu Item 2', callback: () {}),
                          MenuAction(title: 'Menu Item 3', callback: () {}),
                          MenuSeparator(),
                          Menu(title: 'Submenu', children: [
                            MenuAction(
                                title: 'Submenu Item 1', callback: () {}),
                            MenuAction(
                                title: 'Submenu Item 2', callback: () {}),
                            Menu(title: 'Nested Submenu', children: [
                              MenuAction(
                                  title: 'Submenu Item 1', callback: () {}),
                              MenuAction(
                                  title: 'Submenu Item 2', callback: () {}),
                            ]),
                          ]),
                        ],
                      );
                    },
                    child: GestureDetector(
                      onTap: () {
                        //do something
                      },
                      child: Text(""),
                    ),
                  );`

**Comment by knopp** [comment]
I tried this but I can't really reproduce this, at least not with 0.8.4. Does this happen for you with a new Flutter project?

**Comment by onism0106** [comment]
Strangely enough, I don't have this problem when I use a new flutter project, but I do have this problem when I use my own project
