### ISSUE TITLE
[super_native_extensions][irondash_engine_context] Cann't compile at Deepin/UOS (distribution of linux)

### ISSUE THREAD

**Issue by leisu1** [superlistapp/super_native_extensions#269]
the begin error info:
irondash_engine_context_plugin.cc:30:20: error: use of undeclared identifier
'gettid'
[   +1 ms]   main_thread_id = gettid();

when I change the gettid to getpid, then report error:
[   +2 ms] /usr/bin/ld: //home/upchat/Desktop/uct_dtp/build/linux/x64/release/plugins/super_native_extensions/libsuper_native_extensions.so: undefined reference to
`pthread_setspecific@GLIBC_2.34'
[        ] /usr/bin/ld: //home/upchat/Desktop/uct_dtp/build/linux/x64/release/plugins/super_native_extensions/libsuper_native_extensions.so: undefined reference to `dlopen@GLIBC_2.34'
[        ] /usr/bin/ld: //home/upchat/Desktop/uct_dtp/build/linux/x64/release/plugins/super_native_extensions/libsuper_native_extensions.so: undefined reference to `fstat64@GLIBC_2.33'
[        ] /usr/bin/ld: //home/upchat/Desktop/uct_dtp/build/linux/x64/release/plugins/super_native_extensions/libsuper_native_extensions.so: undefined reference to `stat64@GLIBC_2.33'
[        ] /usr/bin/ld: //home/upchat/Desktop/uct_dtp/build/linux/x64/release/plugins/super_native_extensions/libsuper_native_extensions.so: undefined reference to
`pthread_getspecific@GLIBC_2.34'
[   +1 ms] /usr/bin/ld: //home/upchat/Desktop/uct_dtp/build/linux/x64/release/plugins/super_native_extensions/libsuper_native_extensions.so: undefined reference to
`pthread_key_delete@GLIBC_2.34'
[        ] /usr/bin/ld: //home/upchat/Desktop/uct_dtp/build/linux/x64/release/plugins/super_native_extensions/libsuper_native_extensions.so: undefined reference to `gettid@GLIBC_2.30'
[        ] /usr/bin/ld: //home/upchat/Desktop/uct_dtp/build/linux/x64/release/plugins/super_native_extensions/libsuper_native_extensions.so: undefined reference to
`pthread_key_create@GLIBC_2.34'
[        ] /usr/bin/ld: //home/upchat/Desktop/uct_dtp/build/linux/x64/release/plugins/super_native_extensions/libsuper_native_extensions.so: undefined reference to `dlsym@GLIBC_2.34'
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by leisu1** [comment]
The first problem seems to be that the header file is not found
The second problem seems to be that the relevant libraries are not being linked
Is there any solution?

**Comment by knopp** [comment]
gettid and getpid are two completely different methods. I think maybe we're missing `#define _GNU_SOURCE` there.

As for the second error, which super_native_extensions version are you using? Latest build should link with older glibc version.

**Comment by knopp** [comment]
Actually, I think your glibc version is just too old? gettid only been added in glib 2.30. if you run `ldd --version` what output do you get?

**Comment by leisu1** [comment]
> Actually, I think your glibc version is just too old? gettid only been added in glib 2.30. if you run `ldd --version` what output do you get?

You are right. Glib version is 2.28.  I used flutter_quill which depends on super_native_extensions 0.7.3.  Can you do some work to make older versions of glibc compatible? The linux system used by our company are all of this version and will not be upgraded in the short term.

**Comment by leisu1** [comment]
In Deepin/UOS source , we can't update glibc because of  the latest version is 2.28. https://community-packages.deepin.com/deepin/apricot/pool/main/g/glibc/

**Comment by knopp** [comment]
I think `gettid` is the only call that requires glibc 2.30. Given how it is used it should be possible to replace it with pthread_self.

**Comment by knopp** [comment]
Can you let me know if 0.8.1 works for you? You may need to use `dependencty_overrides` if another package depends on older version, i.e.

```yaml
dependency_overrides:
   super_clipboard: ^0.8.1
   super_native_extensions: ^0.8.1
```

(version for both `super_clipboard` and `super_native_extensions` need to be specified)

**Comment by leisu1** [comment]
Yeah，0.8.1 works for me. Thanks!
