### ISSUE TITLE
Issues with Multiple Architectures and GIF Copying on iOS

### ISSUE THREAD

**Issue by mohammadinfo** [superlistapp/super_native_extensions#275]
Hi
I use your extension to copy images to the clipboard. Everything works fine for the complete Android output, but when I use the command "flutter build apk --split-per-abi" to get output for different architectures, nothing works, and copying doesn't happen. Another issue is that I can copy GIFs on Android, but it doesn't work for GIFs on iOS. What should I do?

**Comment by knopp** [comment]
Hi, you need to be more specific in both cases. Do you get any error message? Which architecture are you testing it with? I just looked at apk generated with `--split-per-abi` and for all three supported architectures (arm64, armeabi-v7a and x86_64 native libraries are all there.

As for iOS, can you provide sample code that can be used to reproduce the problem?

**Comment by knopp** [comment]
Actually, I think we might have the uniform type identifier for gif wrong. It's currently `public.gif`, but it should have been `com.compuserve.gif`.

**Comment by mohammadinfo** [comment]
No, I didn't receive any error messages. I tested it on armeabi-v7a, and it didn't copy the image. However, when I use the complete APK (with full architecture), everything works fine.

**Comment by mohammadinfo** [comment]
> Actually, I think we might have the uniform type identifier for gif wrong. It's currently `public.gif`, but it should have been `com.compuserve.gif`.

On Android, we can copy GIFs, but on iOS, it's not possible.

**Comment by knopp** [comment]
Which version did you test it with? Version before 8.1.0 had problems on 32bit architectures.

**Comment by mohammadinfo** [comment]
> Which version did you test it with? Version before 0.8.1 had problems on 32bit architectures.

This version : super_clipboard: ^0.7.3

**Comment by knopp** [comment]
Can you try 0.8.1? 0.7.3 does not correctly work on 32bit systems.

**Comment by mohammadinfo** [comment]
> Can you try 0.8.1? 0.7.3 does not correctly work on 32bit systems.

Yes, I'll test it.
Thank you very much indeed 🙏🌹

**Comment by mohammadinfo** [comment]
I tested it on iOS 17 and found that it couldn't copy GIFs, but I was able to copy images.

**Comment by knopp** [comment]
Gif issue should be fixed once 0.8.2 is released.

**Comment by knopp** [comment]
Please reopen if you still have problem after 0.8.2.

**Comment by mohammadinfo** [comment]
I tested and it's fix right now, thanks.
