### ISSUE TITLE
Unable to build with version 0.8.1 

### ISSUE THREAD

**Issue by mohammadinfo** [superlistapp/super_native_extensions#277]
Hi, I can't use the latest version of your package!
this is my error:
![Screenshot 2023-12-28 102125](https://github.com/superlistapp/super_native_extensions/assets/62583428/d064dfd6-a818-4fcc-b5e9-1f8e716c4b17)

**Comment by knopp** [comment]
You need to upgrade flutter to latest stable version (3.16).
