### ISSUE TITLE
XCode: could not compile `super_native_extensions` (lib) due to 58 previous errors

### ISSUE THREAD

**Issue by mirkancal** [superlistapp/super_native_extensions#279]
I start getting this weird error on iOS 17.2 emulator, flutter 3.16.5. Can anyone point me what is it related?
Not much else in the logs, just error on title and PODS:SEVERE

Latest version of the pluing: 0.8.1

**Comment by knopp** [comment]
Which super_native_extensions version is this with? Can get verbose logs (`flutter run -v`)? Also please don't post logs as screenshots.

**Comment by knopp** [comment]
Hey, this seems like an error that happens with older Rust version. Can you give me the response of `rustc --version`?

Do you still get the failure after `rustup update`?

**Comment by mirkancal** [comment]
@knopp I just manually updated rust, it started to give sandbox, rsync samba issues but seem related to the AppCheck from Firebase.

[Sandbox: rsync.samba (13105) deny(1) file-write-create, Flutter failed to write to a file](https://stackoverflow.com/questions/76590131/error-while-build-ios-app-in-xcode-sandbox-rsync-samba-13105-deny1-file-w)

Fixed that one by setting: ENABLE_USER_SCRIPT_SANDBOXING = NO;

Well I still have build errors but I think now it's not related to the super_native_extensions.
