### ISSUE TITLE
Error building on iOS

### ISSUE THREAD

**Issue by mohammadinfo** [superlistapp/super_native_extensions#287]
Hi
There is an error during the build process on iOS :
![image](https://github.com/superlistapp/super_native_extensions/assets/62583428/96ce2ff0-f67b-4ca3-90a4-97412666377a)

**Comment by knopp** [comment]
If you have rust installed try doing `rustup update`.

Otherwise please post full verbose log (`flutter run -v -d <your device>`) as text, not screenshot.

**Comment by knopp** [comment]
Please reopen if this is still an issue after `rustup update`.
