### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by Zuppa-hub** [superlistapp/super_native_extensions#289]
Hi. 
I am compiling the example from macOs arm.
I get this compile error: 
```
: Error: A value of type 'List<int>' can't be returned from a function with return type 'Uint8List'.
format_conversions.dart:85
 - 'List' is from 'dart:core'.
 - 'Uint8List' is from 'dart:typed_data'.
```
Using the library in my app I get the same error. 
I tried to install rust but it does not solve the problem.

**Comment by knopp** [comment]
Super_native_extensions requires flutter 3.16 (latest stable).
