### ISSUE TITLE
Support formats other than Formats.standardFormats E.g rar

### ISSUE THREAD

**Issue by moohammed-gaber** [superlistapp/super_native_extensions#29]
## I need to support formats other than Formats.standardFormats
![IntelliJ Snippet (14)](https://user-images.githubusercontent.com/59158316/203389274-31652f92-a71e-493b-93b1-35691ebc2865.png)
## That's what I tried:
![IntelliJ Snippet (15)](https://user-images.githubusercontent.com/59158316/203390019-4ca2ab12-a0d2-4f53-9435-f3ef8e852e3c.png)

**Comment by hatemragab** [comment]
+1

**Comment by hatemragab** [comment]
Iam waiting
