### ISSUE TITLE
Unable to build cargo kit if package cache and flutter projects on different drives on Windows.

### ISSUE THREAD

**Issue by holyslon** [superlistapp/super_native_extensions#290]
When gradle plugin runs [run_build_tool.cmd](https://github.com/superlistapp/super_native_extensions/blob/444075d11538d5cd15d09536508822a92216892c/super_native_extensions/cargokit/run_build_tool.cmd) it passes to script env variable `%CARGOKIT_TOOL_TEMP_DIR%`. Then sctipt make `cd` to dir that passed inside this variable. But if this variable points to directory that located on different drive than working directory for script, cd will not work. For it to work we need to pass `/D` parameter to `cd`. I made this change localy and it helps. Right now line [11](https://github.com/superlistapp/super_native_extensions/blob/444075d11538d5cd15d09536508822a92216892c/super_native_extensions/cargokit/run_build_tool.cmd#L11) in my script looks like:
```
cd /D "%CARGOKIT_TOOL_TEMP_DIR%"
```
How i can contribute this changes to repo?

**Comment by knopp** [comment]
Hey! Can you make a PR for this here?

https://github.com/irondash/cargokit

Thanks!

**Comment by holyslon** [comment]
Sure

**Comment by holyslon** [comment]
Done.

**Comment by knopp** [comment]
Should be fixed in 0.8.3.
