### ISSUE TITLE
Build issues on Android

### ISSUE THREAD

**Issue by ellet0** [superlistapp/super_native_extensions#291]
We have a open source project called Flutter quill and it depends on this open source project because the editor needs the clipboard to interact with it

We have many reports that tell us they can't build on Android, I think the issue only on Windows but I'm not sure

- [Can't build android windows only](https://github.com/singerdmx/flutter-quill/issues/1670)
- [Strange behavior when compiling on Android](https://github.com/singerdmx/flutter-quill/issues/1655)

![image](https://github.com/superlistapp/super_native_extensions/assets/73608287/25eb6929-495c-4110-aae8-208ee385d4ad)

![image](https://github.com/superlistapp/super_native_extensions/assets/73608287/d296881e-2a29-40a9-a9c7-bf0762e404a9)

```console

Compiling bin/build_tool_runner.dart to kernel file bin/build_tool_runner.dill.
Error: Couldn't resolve the package 'build_tool' in 'package:build_tool/build_tool.dart'.
bin/build_tool_runner.dart:1:8: Error: Not found: 'package:build_tool/build_tool.dart'
import 'package:build_tool/build_tool.dart' as build_tool;
^
bin/build_tool_runner.dart:3:15: Error: Method not found: 'runMain'.
build_tool.runMain(args);
^^^^^^^
Could not find a command named "bin\build_tool_runner.dill".

```

**Comment by knopp** [comment]
Is there any possibility that pub cache is on different drive then the project?

**Comment by knopp** [comment]
Can you retry with 0.8.3? It has a possible fix and additional logging that prints current directory before doing pub get.

**Comment by ellet0** [comment]
> Can you retry with 0.8.3? It has a possible fix and additional logging that prints current directory before doing pub get.

![296979627-7e31ef3d-54db-4009-958d-dec877236e1c.png](https://github.com/superlistapp/super_native_extensions/assets/73608287/79d78ecf-7e7c-4885-8dd7-153a249e1fe0)

Same issue with 0.8.3

**Comment by knopp** [comment]
Thanks. Could you provide verbose logs? (`flutter run -v -d <your-device-id>`)?

**Comment by ellet0** [comment]
> Also, does this happen when you run the app from command line, or only from android studio?

Both

**Comment by ellet0** [comment]
> Thanks. Could you provide verbose logs? (`flutter run -v -d <your-device-id>`)?

[LogsFile](https://github.com/singerdmx/flutter-quill/files/13952830/flutterRunV_exported.txt)

**Comment by knopp** [comment]
My bad. Looks like the cargokit failing is part of engine context, which I forgot to update. It also seems like your project is on different drive, which means that the fix *should* address this, once rolled it.

**Comment by knopp** [comment]
Can you retry with 0.8.4?

**Comment by ellet0** [comment]
> My bad. Looks like the cargokit failing is part of engine context, which I forgot to update. It also seems like your project is on different drive, which means that the fix _should_ address this, once rolled it.

Actually it's not my project, I can't even reproduce the bug, I'm in contact with the users who caught the bug

**Comment by ellet0** [comment]
> Can you retry with 0.8.4?

Huge thanks.
One user said it fixed, I think we are safe to close the issue as completed, but I might re open if the other issue wasn't fixed

**Comment by ellet0** [comment]
> Can you retry with 0.8.4?

Hi again

![297347574-13ae762b-41bd-47bc-af08-23b0518e15d9.png](https://github.com/superlistapp/super_native_extensions/assets/73608287/372e11d9-3503-473f-82bd-ddb8c552788e)

irondash_engine_context can be built normally, but super_native_extensions will still fail to build

For more info and a log file, please take a look at [https://github.com/singerdmx/flutter-quill/issues/1655#issuecomment-1895524675](this)?

**Comment by knopp** [comment]
> > Can you retry with 0.8.4?
> 
> Hi again
> 
> ![297347574-13ae762b-41bd-47bc-af08-23b0518e15d9.png](https://private-user-images.githubusercontent.com/73608287/297348602-372e11d9-3503-473f-82bd-ddb8c552788e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODgwMzEsIm5iZiI6MTcwNTQ4NzczMSwicGF0aCI6Ii83MzYwODI4Ny8yOTczNDg2MDItMzcyZTExZDktMzUwMy00NzNmLTgyYmQtZGRiOGM1NTI3ODhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEwMzUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNTkxOGU1Zjg1YzE4MTg3ZGExZmQ1OTkzNGI5OGI0OTk3ZDAzYjZlMDhhY2UxY2E0ZDI5YjAyYThhZDRiNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.myrHhgIHy5jw1cIdTV_NvHMwAmPRL1uDKnflLhhXZ4A)
> 
> irondash_engine_context can be built normally, but super_native_extensions will still fail to build
> 
> For more info and a log file, please take a look at [this](https://github.com/singerdmx/flutter-quill/issues/1655#issuecomment-1895524675)?

Thanks. Commented on the issue. It appears the the user has Rust installed without MSVC build tools (or MSVC). Which is a bit strange, as it should be either none or both installed.

**Comment by ellet0** [comment]
> > > Can you retry with 0.8.4?
> > 
> > Hi again
> > 
> > ![297347574-13ae762b-41bd-47bc-af08-23b0518e15d9.png](https://private-user-images.githubusercontent.com/73608287/297348602-372e11d9-3503-473f-82bd-ddb8c552788e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODgwMzEsIm5iZiI6MTcwNTQ4NzczMSwicGF0aCI6Ii83MzYwODI4Ny8yOTczNDg2MDItMzcyZTExZDktMzUwMy00NzNmLTgyYmQtZGRiOGM1NTI3ODhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEwMzUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNTkxOGU1Zjg1YzE4MTg3ZGExZmQ1OTkzNGI5OGI0OTk3ZDAzYjZlMDhhY2UxY2E0ZDI5YjAyYThhZDRiNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.myrHhgIHy5jw1cIdTV_NvHMwAmPRL1uDKnflLhhXZ4A)
> > 
> > irondash_engine_context can be built normally, but super_native_extensions will still fail to build
> > 
> > For more info and a log file, please take a look at [this](https://github.com/singerdmx/flutter-quill/issues/1655#issuecomment-1895524675)?
> 
> Thanks. Commented on the issue. It appears the the user has Rust installed without MSVC build tools (or MSVC). Which is a bit strange, as it should be either none or both installed.

It might be useful to mention this in the README so new users know this and can solve it easily

I can send a PR if you want
