### ISSUE TITLE
super_clipboard get copied image very complicated

### ISSUE THREAD

**Issue by lucasjinreal** [superlistapp/super_native_extensions#294]
from the example, this seems the main to get image:

```dart
extension IntersperseExtensions<T> on Iterable<T> {
  Iterable<T> intersperse(T element) sync* {
    final iterator = this.iterator;
    if (iterator.moveNext()) {
      yield iterator.current;
      while (iterator.moveNext()) {
        yield element;
        yield iterator.current;
      }
    }
  }
}


```

Does there any simpler API such as reader.getImage() and just directly return the uint8 list or ImageProvider etc?

**Comment by knopp** [comment]
This has nothing to do with getting the image. To get the image you call `reader.getFile` and then you can get the data from the file you get in the callback.

https://github.com/superlistapp/super_native_extensions/tree/main/super_clipboard#reading-from-clipboard

**Comment by lucasjinreal** [comment]
thank u, will try it!
