### ISSUE TITLE
Update to js ^0.7.0

### ISSUE THREAD

**Issue by jezell** [superlistapp/super_native_extensions#295]
The latest super_native_extensions depend on js ^0.6.* which are now outdated, preventing the use of any packages that use the current version of js interop.

**Comment by knopp** [comment]
Do you depend on any package that is using 0.7? I looked at it and quite a lot of packages are still on 0.6.

**Comment by jezell** [comment]
@knopp we do, and any new package that uses js is going to start on 0.7.0 as well. People that want 0.6.0 can put this in their package.json and be ok if no 0.7.0 specific features are used by super_native_extensions and they depend on out of date packages:

```yaml
dependency_overrides:
  js: ^0.6.0
```

Mainly 0.7.0 solves just some naming conflicts with other packages, so I'd guess almost everyone will be updating to it  before too long:

https://github.com/dart-lang/sdk/commit/121d54f1e01eff5c908a1cec7763ceae383fec00

**Comment by knopp** [comment]
I think at this point we should migrate to js_interop and package web instead.
