### ISSUE TITLE
Formats does not exist

### ISSUE THREAD

**Issue by appinteractive** [superlistapp/super_native_extensions#30]
Hey I tried to use the drag and drop extension in may desktop app but with no luck. Trying to get the example working I get stopped by the `Formats` class which does not exists and die dart analyzer does not find. What Im doing wrong here? Is there some step missing?

**Comment by knopp** [comment]
Format class is [here](https://github.com/superlistapp/super_native_extensions/blob/4d21432d40765771aa1f674f10b515ba08586c64/super_clipboard/lib/src/standard_formats.dart).

I'm unable to help you without having more details about what you're trying to do exactly .

**Comment by appinteractive** [comment]
Ahh okay so to be able to use drag and drop, I need to also add the clipboard package. That's a bit confusing, why does that package don't import that core component in both package so there is no cross dependency?

**Comment by knopp** [comment]
Drag and drop should probably reexport relevant bits from clipboard. I'll look into it.
