### ISSUE TITLE
Super_Context_Menu Missing changelogs?

### ISSUE THREAD

**Issue by dannyglover** [superlistapp/super_native_extensions#300]
https://pub.dev/packages/super_context_menu/changelog

Between 0.8.0 and 0.8.4 there has only been one changelog entry (for v0.8.3 updated cargokit).
I'm currently on v0.8.2 in my project, has there been anything significant of note (mainly interested in bug fixes) between that and the latest version?

Thanks @knopp

**Comment by knopp** [comment]
Unfortunately melos change-log generation does not seem to play very nice with upstream dependency changes. Or maybe I'm just holding it wrong. Last few releases were mostly fixing build issues for some users on Windows.

**Comment by dannyglover** [comment]
> Unfortunately melos change-log generation does not seem to play very nice with upstream dependency changes. Or maybe I'm just holding it wrong. Last few releases were mostly fixing build issues for some users on Windows.

No worries. Thanks for the info !
