### ISSUE TITLE
Failing implicit conversion of List<int> to Uint8List in super_clipboard

### ISSUE THREAD

**Issue by davidsanda** [superlistapp/super_native_extensions#302]
Super_clipboard format_conversions.dart does not contain implicit conversion and it fails to compile. Maybe some new dart issue?
It needs to be changed to:
return Uint8List.fromList(utf8.encode(buffer.toString())) on line  85
Same situation on line 89 and also in reader_internal.dart on line 184.

**Comment by knopp** [comment]
Which Flutter version are you using? Super_clipboard requires 3.16 or newer (latest stable).
