### ISSUE TITLE
Support .m4a file type

### ISSUE THREAD

**Issue by lelandtsc** [superlistapp/super_native_extensions#304]
Currently m4a type cannot be found in standardFormats. On Android and ChromeOS,  the file's format identifier will be identified as 'audio/mpeg' which is the same as mp3 file.

Is there any chance that the m4a file will be supported that could make distinction between m4a and mp3 file?

Love this package and thank you for the great support.

**Comment by knopp** [comment]
`m4a` should have mime type of `audio/mp4` and is indeed missing in Formats.

**Comment by lelandtsc** [comment]
Do you mean it will be added for future release?

**Comment by knopp** [comment]
Yes, I'l try to make a PR for it soon.
