### ISSUE TITLE
Can't build archive ios 

### ISSUE THREAD

**Issue by KP-story** [superlistapp/super_native_extensions#307]
HI,i encounter the  problem. 'SEVERE:1:1 could not compile `super_native_extensions` (lib) due to 58 previous errors' when I built archive to release app  but the debug version builds fine. I tried to update rust , flutter but still same errors
---

----rust version 
  stable-aarch64-apple-darwin unchanged - rustc 1.75.0 (82e1608df 2023-12-21)

------------------------------------flutter doctor -v             
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.2.1 23C71 darwin-arm64, locale en-VN)
    • Flutter version 3.16.8 on channel stable at /Users/bap/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (2 weeks ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/bap/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • 29E4AACA-90CF-4AF5-A36D-5144B4869631 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by knopp** [comment]
Can you post here verbose logs? (`flutter build ios --release -v`). I'll take a look.

**Comment by KP-story** [comment]
[output.txt](https://github.com/superlistapp/super_native_extensions/files/14127837/output.txt)
ofcourse, this is my logs.

**Comment by KP-story** [comment]
> Can you post here verbose logs? (`flutter build ios --release -v`). I'll take a look.

ofcourse, this is my logs.
[output.txt](https://github.com/superlistapp/super_native_extensions/files/14127865/output.txt)

**Comment by knopp** [comment]
Thanks. Can you also post output of `rustup +nightly show`? Nightly rust is used for release build to get smallest binary size. It is possible that your stable rust is updated but nightly is not.

**Comment by knopp** [comment]
Or you can just give me output of ` rustup update`.

**Comment by KP-story** [comment]
> Thanks. Can you also post output of `rustup +nightly show`? Nightly rust is used for release build to get smallest binary size. It is possible that your stable rust is updated but nightly is not.

Thank you! I updated to the nightly version, and it was successful. I appreciate your help.

**Comment by dahvlhldle** [comment]
I face the same problem.
debug is fine ,but archive error.

> =/usr/bin/env
Resolving dependencies
Got socket error trying to find package meta at https://pub.dev.
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by knopp** [comment]
> =/usr/bin/env
Resolving dependencies
Got socket error trying to find package meta at https://pub.dev/.
Command PhaseScriptExecution failed with a nonzero exit code

That seems like a network error when connecting to pub?
