### ISSUE TITLE
Can't build on Linux

### ISSUE THREAD

**Issue by ellet0** [superlistapp/super_native_extensions#308]
First of all, I'm not sure if this my issue or a bug

[Full verbose log](https://github.com/singerdmx/flutter-quill/actions/runs/7795147904/job/21257613962?pr=1722)

**Comment by knopp** [comment]
This does not seem to be related to `super_native_extensions` in any way:

```
arting due to {}
[        ] [   +1 ms] Embedding native assets mapping /home/runner/work/flutter-quill/flutter-quill/example/.dart_tool/flutter_build/ef3143aeb09bd082c9b722a91f74844d/native_assets.yaml in kernel.
[   +3 ms] [  +14 ms] /opt/hostedtoolcache/flutter/stable-3.16.9-x64/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/hostedtoolcache/flutter/stable-3.16.9-x64/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root /opt/hostedtoolcache/flutter/stable-3.16.9-x64/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies -DCI=true -Ddart.vm.profile=false -Ddart.vm.product=true --aot --tfa --target-os linux --packages /home/runner/work/flutter-quill/flutter-quill/example/.dart_tool/package_config.json --output-dill /home/runner/work/flutter-quill/flutter-quill/example/.dart_tool/flutter_build/ef3143aeb09bd082c9b722a91f74844d/app.dill --depfile /home/runner/work/flutter-quill/flutter-quill/example/.dart_tool/flutter_build/ef3143aeb09bd082c9b722a91f74844d/kernel_snapshot.d --source file:///home/runner/work/flutter-quill/flutter-quill/example/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart -Dflutter.dart_plugin_registrant=file:///home/runner/work/flutter-quill/flutter-quill/example/.dart_tool/flutter_build/dart_plugin_registrant.dart --native-assets /home/runner/work/flutter-quill/flutter-quill/example/.dart_tool/flutter_build/ef3143aeb09bd082c9b722a91f74844d/native_assets.yaml --verbosity=error package:example/main.dart
[   +1 ms] [   +2 ms]   Future<void> putImageBytes(Uint8List bytes, {String? album}) =>
[        ] [        ]                ^
[        ] [        ] /opt/hostedtoolcache/flutter/stable-3.16.9-x64/.pub-cache/hosted/pub.dev/gal-2.3.0/lib/src/gal_platform_interface.dart:23:16: Context: This is the overridden method ('putImageBytes').
[        ] [        ]   Future<void> putImageBytes(Uint8List bytes,
[        ] [        ]                ^
[        ] [+33219 ms] Persisting file store
[        ] [   +3 ms] Done persisting file store
[        ] [   +3 ms] Target kernel_snapshot failed: Exception
[        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:270:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
[  +22 ms]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
[        ]            <asynchronous suspension>
[        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
[        ]            <asynchronous suspension>
[        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
[        ]            <asynchronous suspension>
[        ]            #6      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
[        ]            <asynchronous suspension>
[        ]            #7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
[        ]            <asynchronous suspension>
[        ]            #8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
[        ]            <asynchronous suspension>
[        ]            #9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:317:32)
[        ]            <asynchronous suspension>
[        ]            #10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
[        ]            <asynchronous suspension>
[        ]            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]            <asynchronous suspension>
[        ]            #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
[        ]            <asynchronous suspension>
[        ]            #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
[        ]            <asynchronous suspension>
[        ]            #16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
[        ]            <asynchronous suspension>
[        ]            #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #18     main (package:flutter_tools/executable.dart:90:3)
[        ]            <asynchronous suspension>
[        ] [  +25 ms] "flutter assemble" took 40,648ms.
[        ] [   +3 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:334:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:90:3)
[        ]            <asynchronous suspension>
[        ] [   +1 ms] ensureAnalyticsSent: 0ms
[        ] [        ] Running 0 shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +1 ms] exiting with code 1
```

**Comment by ellet0** [comment]
> This does not seem to be related to `super_native_extensions` in any way:
> 
> ```
> arting due to {}
> [        ] [   +1 ms] Embedding native assets mapping /home/runner/work/flutter-quill/flutter-quill/example/.dart_tool/flutter_build/ef3143aeb09bd082c9b722a91f74844d/native_assets.yaml in kernel.
> [   +3 ms] [  +14 ms] /opt/hostedtoolcache/flutter/stable-3.16.9-x64/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/hostedtoolcache/flutter/stable-3.16.9-x64/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root /opt/hostedtoolcache/flutter/stable-3.16.9-x64/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies -DCI=true -Ddart.vm.profile=false -Ddart.vm.product=true --aot --tfa --target-os linux --packages /home/runner/work/flutter-quill/flutter-quill/example/.dart_tool/package_config.json --output-dill /home/runner/work/flutter-quill/flutter-quill/example/.dart_tool/flutter_build/ef3143aeb09bd082c9b722a91f74844d/app.dill --depfile /home/runner/work/flutter-quill/flutter-quill/example/.dart_tool/flutter_build/ef3143aeb09bd082c9b722a91f74844d/kernel_snapshot.d --source file:///home/runner/work/flutter-quill/flutter-quill/example/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart -Dflutter.dart_plugin_registrant=file:///home/runner/work/flutter-quill/flutter-quill/example/.dart_tool/flutter_build/dart_plugin_registrant.dart --native-assets /home/runner/work/flutter-quill/flutter-quill/example/.dart_tool/flutter_build/ef3143aeb09bd082c9b722a91f74844d/native_assets.yaml --verbosity=error package:example/main.dart
> [   +1 ms] [   +2 ms]   Future<void> putImageBytes(Uint8List bytes, {String? album}) =>
> [        ] [        ]                ^
> [        ] [        ] /opt/hostedtoolcache/flutter/stable-3.16.9-x64/.pub-cache/hosted/pub.dev/gal-2.3.0/lib/src/gal_platform_interface.dart:23:16: Context: This is the overridden method ('putImageBytes').
> [        ] [        ]   Future<void> putImageBytes(Uint8List bytes,
> [        ] [        ]                ^
> [        ] [+33219 ms] Persisting file store
> [        ] [   +3 ms] Done persisting file store
> [        ] [   +3 ms] Target kernel_snapshot failed: Exception
> [        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:270:7)
> [        ]            <asynchronous suspension>
> [        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
> [        ]            <asynchronous suspension>
> [        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
> [  +22 ms]            <asynchronous suspension>
> [        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
> [        ]            <asynchronous suspension>
> [        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
> [        ]            <asynchronous suspension>
> [        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
> [        ]            <asynchronous suspension>
> [        ]            #6      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
> [        ]            <asynchronous suspension>
> [        ]            #7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
> [        ]            <asynchronous suspension>
> [        ]            #8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
> [        ]            <asynchronous suspension>
> [        ]            #9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:317:32)
> [        ]            <asynchronous suspension>
> [        ]            #10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
> [        ]            <asynchronous suspension>
> [        ]            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> [        ]            <asynchronous suspension>
> [        ]            #12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
> [        ]            <asynchronous suspension>
> [        ]            #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
> [        ]            <asynchronous suspension>
> [        ]            #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> [        ]            <asynchronous suspension>
> [        ]            #15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
> [        ]            <asynchronous suspension>
> [        ]            #16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
> [        ]            <asynchronous suspension>
> [        ]            #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> [        ]            <asynchronous suspension>
> [        ]            #18     main (package:flutter_tools/executable.dart:90:3)
> [        ]            <asynchronous suspension>
> [        ] [  +25 ms] "flutter assemble" took 40,648ms.
> [        ] [   +3 ms] 
> [        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
> [        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:334:7)
> [        ]            <asynchronous suspension>
> [        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
> [        ]            <asynchronous suspension>
> [        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> [        ]            <asynchronous suspension>
> [        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
> [        ]            <asynchronous suspension>
> [        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
> [        ]            <asynchronous suspension>
> [        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> [        ]            <asynchronous suspension>
> [        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
> [        ]            <asynchronous suspension>
> [        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
> [        ]            <asynchronous suspension>
> [        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> [        ]            <asynchronous suspension>
> [        ]            #10     main (package:flutter_tools/executable.dart:90:3)
> [        ]            <asynchronous suspension>
> [        ] [   +1 ms] ensureAnalyticsSent: 0ms
> [        ] [        ] Running 0 shutdown hooks
> [        ] [        ] Shutdown hooks complete
> [        ] [   +1 ms] exiting with code 1
> ```

Oh sorry

**Comment by knopp** [comment]
No worries, but this seems like it might be a bug in dart compiler...
