### ISSUE TITLE
[iOS] Error when accessing DataReader

### ISSUE THREAD

**Issue by EgorK0rshun** [superlistapp/super_native_extensions#311]
Only in release mode. On build from TestFlight it is always reproduced

```
Invalid argument(s): Failed to lookup symbol 'super_native_extensions_init_message_channel_context': dlsym(RTLD_DEFAULT, super_native_extensions_init_message_channel_context): symbol not found
```

https://github.com/superlistapp/super_native_extensions/issues/309#issuecomment-1932769768

**Comment by stepushchik** [comment]
There no `.so` files in TestFlight version, we have 
`.../Products/Applications/Runner.app/Frameworks/App.framework/App` file and
```
ïæ≤æ.22”£˛r ,TextInputConfiguration2‚•˛p6>2B5=L2”¶˛T,_setVisible@13643962352‚¶˛6C"2“™˛(get:isDelete2‘±˛∫)J_shouldAnimateNoteDeletion@10283043362‰≤˛‘&.J7AB0=>2O20=5 =0 40==82÷¥˛Ã>ê__TabBackupSyncIconState&State&SingleTickerProviderStateMixin@10372236992”∑˛¯;,RawReceivePort_factory2‚∫˛Iskoaeno2”æ˛¢6"get:configuration2“√˛8ImageFormat.2‚≈˛†<:2V2“œ˛æ4SpringType2‚–˛Ã+A5=BO1@O2’—˛ hsuper_native_extensions_init_message_channel_context2“’˛5 _sendOOB@10262482’÷˛|h_FlutterError&Error&DiagnosticableTreeMixin@400226082“◊˛z:H:mm2‘Ÿ˛∆ Zget:_handleMoveCursorBackwardByWord@3672456032”⁄˛d2:application/vnd.clonk.c4group2“€˛Ó"isSuccess2“‡˛T<Alignment(2“·˛∆$Az ÷n neve:2”„˛ƒ4Cau $modalRouteContentName2“Â˛H0cacute;2‘Ê˛∫NLottie only supports bodymovin >= 4.4.02”Ê˛66SceneBuilder::pushClipRRect2“Ì˛Ï,\\(\S)2“Ì˛$(&sscr;2“Ô˛|°Entendido!2“˛^stickerType2‚˛ƒ2”Ô˛$0,trackAddBackgroundSave2”Ô˛x>application/vnd.mozilla.xul+xml2“˙˛Œ#FrameRate(2‚˛˛∫2ÿ∞›2‚ˇ˛*ê"82‚ˇ¿X2”ˇ40_lengthFromPath@140693162‚ˇ22“ˇ¨%Action2“
ˇ~rootNavigator2“ˇ2 EEE, y-M-d2”ˇB+.get:onboardingTipsTitle2‚ˇX
Ç
```
in it.

**Comment by EgorK0rshun** [comment]
it looks like `super_native_extensions_init_message_channel_context2` . Maybe problem in `2`?

**Comment by stepushchik** [comment]
![Screenshot 2024-02-09 at 12 58 10 PM](https://github.com/superlistapp/super_native_extensions/assets/58251165/384742b8-6d83-4be2-ac5d-eda0488dc202)

**Comment by knopp** [comment]
Sorry, I meant dylib. There should be a dylib super_native_extensions framework. Using the nm command you should be able to list all symbols inside.

**Comment by knopp** [comment]
Note that the dylib does not have an extension. It's the binary file in the root of the framework.

**Comment by stepushchik** [comment]
There is no super_native_extensions dylib in Frameworks
![Screenshot 2024-02-12 at 5 35 20 PM](https://github.com/superlistapp/super_native_extensions/assets/58251165/2bd69bec-b1c1-44f7-8006-6a4eacbd9a0d)

**Comment by stepushchik** [comment]
We have some mentions of super_native_extensions in App, but

and `nm -gD App`
output:
```
App:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm: error: App: File format has no dynamic symbol table
```


` nm App
`
output:
```
App:
00000000005e6c40 S _kDartIsolateSnapshotData
000000000000e340 T _kDartIsolateSnapshotInstructions
00000000005de340 S _kDartVmSnapshotData
0000000000004000 T _kDartVmSnapshotInstructions
                 U dyld_stub_binder
```

**Comment by knopp** [comment]
There don't seem to be any frameworks from other flutter plugins. Is super_native_extensions only flutter plugin that you're using?

**Comment by stepushchik** [comment]
We are using a lot of other plugins and there are mentions of them in `App`
For example, sqflite:
![Screenshot 2024-02-12 at 5 43 49 PM](https://github.com/superlistapp/super_native_extensions/assets/58251165/cc4b0114-ba75-4db4-9416-7e9591660fa2)

**Comment by stepushchik** [comment]
Also we have
```
flutter_ios_podfile_setup

target 'Runner' do
  platform :ios, '13.0'
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
end
```

in Podfile

**Comment by knopp** [comment]
```
use_frameworks! :linkage => :static`
```

`super_native_extensions` does not support static linkage. What reason do you have for using static linkage?

**Comment by stepushchik** [comment]
I have removed `:linkage => :static`. It was added for unknown reason from previous project (maybe due to old dependencies). Everything works OK.

Thanks for your time and for `super_native_extensions`!
