### ISSUE TITLE
super_drag_and_drop (Can't Move Items On DropRegion) 

### ISSUE THREAD

**Issue by TheArchitect123** [superlistapp/super_native_extensions#313]
Hi,

Is there anyway (when doing a **Move** operation), to identify the individual item on the DropRegion that the user is selecting without checking against the coordinates?

I have a few items on a simple Photo, that users can drag and drop (these are seperate images themselves).
Each of these images are placed on top of the main photo, and users can either perform a copy operation or a move operation.

The issue is, when moving, I can't seem to identify which image the user is dragging (via move) without tracking its location coordinates and comparing it with the current dragged location vs the coordinates the user is performing a drag on the screen (where they start the drag process).

So the question is:
How can we place unique identifiers on each Drag Widget, so when users select, we can identify their selection with this unique Id?

**Comment by TheArchitect123** [comment]
@knopp @tomgilder @robertodoering @CillianMyles 
Any help here, would be greatly appreciated. Thank you

**Comment by knopp** [comment]
Why not use `localData` for this. When you construct a `DragItem` you can specify localData which is available when dragging over your own application. You can store the unique identifier there.

Also please don't tag random people in the comments.
