### ISSUE TITLE
iOS compilation issue with flutter 3.16.9

### ISSUE THREAD

**Issue by Mikhail-Ivanou** [superlistapp/super_native_extensions#314]
Hi
I get next error once I try to upgrade my project dependencies.
This library is     dependency: transitive.  for me.

Xcode build done.                                           39,4s
Failed to build iOS app
Error (Xcode): could not compile `super_native_extensions` (lib) due to 58 previous errors

I use Flutter 3.16.9
Xcode 15

**Comment by knopp** [comment]
`rustup update` should solve this.

**Comment by Mikhail-Ivanou** [comment]
It helped, thanks!

**Comment by Abhilash-1998** [comment]
How is rustup command used in flutter?
