### ISSUE TITLE
Remove Irondash dependencies

### ISSUE THREAD

**Issue by OpenJarvisAI** [superlistapp/super_native_extensions#315]
Remove Irondash dependencies

**Comment by OpenJarvisAI** [comment]
irondash_engine_context-0.5.2/cargokit/gradle/plugin.gradle' line: 140

* What went wrong:
A problem occurred configuring project ':irondash_engine_context'.
> Failed to notify project evaluation listener.
   > Please set 'android.ndkVersion' in 'app/build.gradle'.

**Comment by OpenJarvisAI** [comment]
Actaully have NDK installed

**Comment by knopp** [comment]
Please read [this part of README](https://github.com/superlistapp/super_native_extensions/tree/main/super_clipboard#android-support).

By default this should already included in Flutter generated `build.gradle`. (It is for any new project)

Cargokit is what build the native part of the project. It can not be removed. It will however be migrated to native assets once available which will remove the gradle plugin dependency.

**Comment by OpenJarvisAI** [comment]
Hey guys.


I am really out of my mind now...

I added super_clipboard dependencies.

And my app goes from 16M to 34M

<img width="305" alt="image" src="https://github.com/superlistapp/super_native_extensions/assets/136460643/68ff5a61-29ea-423a-a495-5ad6956f7439">


holy sh........

**Comment by knopp** [comment]
You might want to take a look at what's inside of the APK. The actual size of release binary for android arm64 is 1.4MB (https://github.com/superlistapp/super_native_extensions/releases)

**Comment by OpenJarvisAI** [comment]
Hi, the supernativeextension .so indeed small, but it introduce many other deps which I don't know what it is.

After remvoe alll superxxx related dependencies and remove all build folder, my app size goes normal.

**Comment by knopp** [comment]
I closed this issue because the conversation continued in https://github.com/superlistapp/super_native_extensions/issues/316.
