### ISSUE TITLE
Avoid using superxxxx any one of this lib, it will make your app HUGE

### ISSUE THREAD

**Issue by OpenJarvisAI** [superlistapp/super_native_extensions#316]
My app usally only 16M.

After added super_clipboard.

 it's now

<img width="305" alt="image" src="https://github.com/superlistapp/super_native_extensions/assets/136460643/97ae6c3f-8647-4f9f-8988-431f1169f3a1">

I AM VERY IMPRESSED

**Comment by knopp** [comment]
You can see the size of the binaries here: https://github.com/superlistapp/super_native_extensions/releases/tag/precompiled_f59b3b795858ab3621a4076cc9be47aa

The release size of arm64 binary is 1.4MB uncompressed. It compressed to about 500kb. Have you tried inspecting the content of the APK? What causes the size increase?

**Comment by OpenJarvisAI** [comment]
That's very weired.


I just analyse a bit.

 found there something, that untrackable... make the whole app.so huge.

<img width="1642" alt="image" src="https://github.com/superlistapp/super_native_extensions/assets/136460643/0429686a-01ef-4398-8aae-bdc2a390cd02">

**Comment by knopp** [comment]
This still wouldn't explain the binary size. What else is in the APK that makes it so big?

**Comment by OpenJarvisAI** [comment]
<img width="1658" alt="image" src="https://github.com/superlistapp/super_native_extensions/assets/136460643/68af1df4-86a0-4888-8218-8db99a173c14">


this the the whole view.


TBH, am pretty new to flutter, I justg found my app goes big suddenly, and this makes me panic!

From above, looks like my src's size should be normal?

<img width="1654" alt="image" src="https://github.com/superlistapp/super_native_extensions/assets/136460643/29c82808-d225-42c3-9694-d7df7ffd82af">


the flutter engine also looks like crazy big.

**Comment by OpenJarvisAI** [comment]
[apk-code-size-analysis_04.json](https://github.com/superlistapp/super_native_extensions/files/14277719/apk-code-size-analysis_04.json)

Do u got any idea?

```
dart devtools --appSizeBase=apk-code-size-analysis_04.json
```

**Comment by knopp** [comment]
The file that you have attached doesn't even contains super_native_extensions.

The APK file is a ZIP file. You can uncompress it and look what is inside.

**Comment by knopp** [comment]
> Hi, the supernativeextension .so indeed small, but it introduce many other deps which I don't know what it is.
> After remvoe alll superxxx related dependencies and remove all build folder, my app size goes normal.

Here are all the dependencies of super_clipboard, including transitive dependencies:
```
dart pub deps -s compact
Dart SDK 3.4.0-140.0.dev
Flutter SDK 3.20.0-7.0.pre.59
clipboard_test 0.1.0

dependencies:
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- super_clipboard 0.8.5 [flutter collection meta super_native_extensions]

dev dependencies:
- flutter_lints 3.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- crypto 3.0.3 [typed_data]
- device_info_plus 9.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 7.0.0 [meta path]
- fixnum 1.1.0
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- irondash_engine_context 0.5.2 [flutter plugin_platform_interface]
- irondash_message_channel 0.6.0 [flutter ffi]
- js 0.6.7 [meta]
- leak_tracker 10.0.4 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.3 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.12.0
- path 1.9.0
- pixel_snap 0.1.5 [flutter]
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- super_native_extensions 0.8.5 [flutter flutter_web_plugins meta ffi collection js path uuid irondash_engine_context irondash_message_channel device_info_plus pixel_snap]
- term_glyph 1.2.1
- test_api 0.7.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- uuid 4.3.3 [crypto sprintf meta fixnum]
- vector_math 2.1.4
- vm_service 14.0.0
- win32 5.2.0 [ffi]
- win32_registry 1.1.2 [ffi win32]
```

It's not the dependency thing. I can see where the problem is. For some reason after adding super_native_extensions the final APK file is **uncompressed**. That shouldn't matter in practice because it will be recompressed by the play store, but it would be good thing to find out why that happens.

**Comment by knopp** [comment]
Okay, so this is a side-effect of `minSdkVersion=23`. See more here: https://github.com/flutter/flutter/issues/139568.

With `minSdkVersion=23` android no longer compresses native binaries in the APK. This is better for performance as they can be loaded directly and (they would have to be decompressed anyway) and play store compresses them during download anyway.

There are some flags that you can use to get old behavior but it doesn't really matter since it makes no difference in practice.

**Comment by knopp** [comment]
If you want to force APK compression you can add the following to your "app/build.gradle":

```
android {
    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }
```

See https://stackoverflow.com/a/73368793.

**Comment by OpenJarvisAI** [comment]
@knopp  am not sure if is the issue.

But minalSDkVersion 33 is bigger than miniaSDKVersion I set previous and currently removed super_exnteions which is 32.

Why a higher version won't compress and lower version compress? 

If so, then the apps all using minialDSKSversion 32 won't compress anymore? This doesn't seems make sense

**Comment by knopp** [comment]
**minSdkVersion<=22.**  - native libraries in APK are compressed, but need to be decompressed on device. so the total space on device is APK size + decompressed binaries

**minSdkVersion>=23** - native libraries in APK are not compressed, but can be loaded on the device directly from APK, so the total space taken on device is smaller than with **minSdkVersion<=22**.

Have you look at **any** of the links that I've posted?

**Comment by OpenJarvisAI** [comment]
I looked, but I don't understand. 

What I care about is the pure APK size. Since that is the product I shipped.

**Comment by knopp** [comment]
The APK size does not matter, because the play store will recompress it anyway. But if you insist on smaller APK size add this to your `app/build.gradle` file

```
android {
    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }
```
And then you should get same APK size regardless of minSdkVersion.

**Comment by OpenJarvisAI** [comment]
thanks, this seems a solution.
