### ISSUE TITLE
[super_context_menu] Menu is clipped on horizontal tablet view

### ISSUE THREAD

**Issue by JGeek00** [superlistapp/super_native_extensions#317]
The context menu is a little bit clipped on horizontal tablet view.
![Screenshot_1709239722](https://github.com/superlistapp/super_native_extensions/assets/47545344/6d6bb5b1-bef0-4c75-859c-db2c046b603e)

On vertical tablet view it's very close to the edge of the screen but it doesn't get clipped
![Screenshot_1709239796](https://github.com/superlistapp/super_native_extensions/assets/47545344/f33cf4b3-c128-46c8-9027-09b8bb0c2873)

On mobile everything is perfect
![Screenshot_1709239828](https://github.com/superlistapp/super_native_extensions/assets/47545344/d5fd0890-034b-4284-8ec6-1bcdbdf2e6fc)

**Comment by knopp** [comment]
Thanks for the report. This is definitely not meant to happen. I'll take a look.

**Comment by JGeek00** [comment]
Let me know if you need more information or a code example
