### ISSUE TITLE
Publish a new version of the updated device_info_plus plugin

### ISSUE THREAD

**Issue by ellet0** [superlistapp/super_native_extensions#340]
I was going to send a PR but it seems you already [did that](https://github.com/superlistapp/super_native_extensions/commit/6737ff24128d1751e537f5013e83f7490f933397)

We really need that as soon as possible as the users in [Flutter Quill](https://github.com/singerdmx/flutter-quill/issues/1783) already expecting this update

Thank you for your time and efforts

**Comment by knopp** [comment]
Hi, I just published 0.8.10.

**Comment by ellet0** [comment]
> Hi, I just published 0.8.10.

Thanks
