### ISSUE TITLE
[super_clipnboard] Undefined name 'SystemClipboard'

### ISSUE THREAD

**Issue by ioma8** [superlistapp/super_native_extensions#345]
I did install the super_clipboard, added ndk version to build.gradle etc. Build of the app works. However I cant use super_clipboard as the SystemClipboard object is not found nor by ide nor by flutter. I am getting this message:
`Undefined name 'SystemClipboard' `
<img width="475" alt="image" src="https://github.com/superlistapp/super_native_extensions/assets/6624752/eb0edd12-2715-4b38-bb7c-bdc41b1301da">
```
> Task :app:compileFlutterBuildDebug
lib/widgets/mywidget.dart:200:23: Error: The getter 'SystemClipboard' isn't defined for the class '_MyWidgetState'.
 - '_MyWidgetState' is from 'package:mcrm/widgets/mywidget.dart' ('lib/widgets/mywidget.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'SystemClipboard'.
    final clipboard = SystemClipboard.instance;
```

Yes, I have `import 'package:super_clipboard/super_clipboard.dart';` at the top of the file.

I am on MacOs 14.2.1.

**Comment by knopp** [comment]
It is possible that something else exports `SysrtemClipboard`? Can you post here more of the file?

**Comment by ioma8** [comment]
No, nothing else exports SystemClipboard. As a workaround I will use this code:
```
final clipboard = ClipboardWriter.instance;
```

I have searched the complete downloaded package super_clipboard and there is not single export of any SystemClipboard symbol. Its either bug in how you have distributed the package or Instructions on https://pub.dev/packages/super_clipboard need to get updated to use ClipboardWriter instead of SystemClipboard. Object SystemClipboard is non-existent in your package as it is currently distributed by pub dev.

**Comment by ioma8** [comment]
Now I see my `flutter pub add super_clipboard` installed me version 0.7.0 instead of the latest 0.8.11. I am not sure why this happened?

**Comment by ioma8** [comment]
Okay so this is my mistake, I have old Dart SDK which forced 0.7.0 version of super_clipboard which has different api. Closing this issue and sorry.
