### ISSUE TITLE
[super_clipboard] ctrl+v after restart machine with did not ctrl+c/copy operation would make app crash

### ISSUE THREAD

**Issue by lazycoding** [superlistapp/super_native_extensions#367]
[super_clipboard] ctrl+v after restart machine with did not ctrl+c/copy operation would make app crash

system: linux
error:
[0521/103620. 037775: ERROR: browser_main_loop. cc(274)] Gtk: gtk_targets include_text: assertion 'targets 1= NULL || n_targets == 0
failed

thread '‹unnamed»' panicked at /home/runner/ rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/sIc/rust/library/all

oc/sIC/raw_vec.Is:25:5:
capacity overflow

**Comment by boyan01** [comment]
this should fixed by https://github.com/superlistapp/super_native_extensions/pull/393
