### ISSUE TITLE
[Android][deprecation] view.startDrag(ClipData,DragShadowBuilder,Object,int)  is deprecation in sdk 24 use view.startDragAndDrop instead

### ISSUE THREAD

**Issue by zhibisora** [superlistapp/super_native_extensions#368]
view.startDrag(ClipData,DragShadowBuilder,Object,int)  is deprecation in sdk 24 use view.startDragAndDrop instead

https://stackoverflow.com/questions/39596889/startdrag-method-deprecated-and-unable-to-compile-the-program

**Comment by zhibisora** [comment]
Should I make a pr for this issue？

**Comment by knopp** [comment]
Please do, PRs are always welcome :)
