### ISSUE TITLE
[macOS/Windows] Support multiple drag items

### ISSUE THREAD

**Issue by leonx98** [superlistapp/super_native_extensions#37]
I haven't found a way to drag multiple drag items (especially virtual files) on desktop. Is this possible?

**Comment by leonx98** [comment]
Hey Matej,
thanks for your quick response!

I saw hints in the code that it might be possible, but I was not entirely sure.
We have an application and want to allows us to drag and drop files (virtual files because the content exist on a remote location) within and outside of the application (e.g to the Finder).
We tried out your great plugin and currently using just a single drag item. An example where you can drag multiple drag items (each with a virtual file) would be great!

**Comment by knopp** [comment]
So in general, for dragging multiple items there are two options:

1. Use `BaseDraggableWidget`. This will give you most flexibility - you can construct `DragConfiguration` from scratch, with as many items as you want. The downside is that you'll be responsible for providing the drag images as well, which is more work.

2. Use multiple `DragItemWidget`s - each one for one dragged item, and specify the `dragItemsProvider` to `DraggableWidget` in order to provide the `DragItemWidgets` that you want to drag. 

Example:

```dart
class _MyHomePageState extends State<MyHomePage> {
  final dragItem1 = GlobalKey<DragItemWidgetState>();
  final dragItem2 = GlobalKey<DragItemWidgetState>();
  final dragItem3 = GlobalKey<DragItemWidgetState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          DragItemWidget(
            key: dragItem1,
            dragItemProvider: (image, _) async => DragItem(
              image: await image(),
            ),
            allowedOperations: () => const [DropOperation.copy],
            //
            // Dragging this item will also drag the other two items
            //
            child: DraggableWidget(
              dragItemsProvider: (context) => [
                dragItem1.currentState!,
                dragItem2.currentState!,
                dragItem3.currentState!,
              ],
              child: Container(
                decoration: BoxDecoration(
                  color: Colors.blue,
                  borderRadius: BorderRadius.circular(10),
                ),
                padding: const EdgeInsets.all(20),
                child: const Text("Item 1"),
              ),
            ),
          ),
          const SizedBox(height: 10),
          DragItemWidget(
            key: dragItem2,
            dragItemProvider: (image, _) async => DragItem(
              image: await image(),
            ),
            allowedOperations: () => const [DropOperation.copy],
            child: Container(
              decoration: BoxDecoration(
                color: Colors.green,
                borderRadius: BorderRadius.circular(10),
              ),
              padding: const EdgeInsets.all(20),
              child: const Text("Item 2"),
            ),
          ),
          const SizedBox(height: 10),
          DragItemWidget(
            key: dragItem3,
            dragItemProvider: (image, _) async => DragItem(
              image: await image(),
            ),
            allowedOperations: () => const [DropOperation.copy],
            child: Container(
              decoration: BoxDecoration(
                color: Colors.red,
                borderRadius: BorderRadius.circular(10),
              ),
              padding: const EdgeInsets.all(20),
              child: const Text("Item 3"),
            ),
          )
        ],
      ),
    );
  }
}
```

This will produce something like this:
 
<img width="115" alt="Screenshot 2023-01-03 at 20 28 17" src="https://user-images.githubusercontent.com/96958/210427499-d1fa700f-174d-448d-b819-af521f89c568.png">

Where dragging "Item1" will drag all 3 items. Each of the item can be a virtual file (see `virtualFileDragItem` function in the example).

**Comment by leonx98** [comment]
Thanks for the example code! 😃 I will let you know if something doesn't work.

**Comment by knopp** [comment]
Closing this for now. Please reopen if you have problems dragging multiple files.

**Comment by prinkeeras** [comment]
Hi, can you please provide example using `BaseDraggableWidget`?
