### ISSUE TITLE
[super_context_menu] On macos, How to get the notification of onmenushow

### ISSUE THREAD

**Issue by xinlee333** [superlistapp/super_native_extensions#374]
I read the code, and it seems like only mobile platforms can receive the onMenuShow notification. How can I receive the notification on desktop platforms? Please help me.

**Comment by knopp** [comment]
I just tried this:
```dart
      menuProvider: (req) {
        req.onShowMenu.addListener(() {
          print('Menu shown');
        });
        return Menu(
```
seems to work as expected on macOS. Can you post some code?

**Comment by xinlee333** [comment]
I made it! I'm a beginner who transitioned from C++ to Flutter, and I'm very grateful for your help.
