### ISSUE TITLE
ContextMenuWidget child appears when scrolling 

### ISSUE THREAD

**Issue by mjurfest** [superlistapp/super_native_extensions#383]
Every list item has a `ContextMenuWidget`, so when scrolling if the gesture to scroll quickly taps on a list item too, then the child (list item) slightly appears while scrolling.

Please check the video to understand better.
https://github.com/superlistapp/super_native_extensions/assets/17320967/4d5ea641-629b-415c-8f0b-b2db90bab21d

When scrolling without tapping on the item it works fine.
Is it a bug or i can somehow set up this?

**Comment by knopp** [comment]
This is a bug. Working on it now.

**Comment by knopp** [comment]
This should be fixed in 0.8.17.

**Comment by mjurfest** [comment]
Thanks for the quick fix, it's working fine now 👍
