### ISSUE TITLE
Starting the app stalls on "Installing NDK 23.1.7779620" after installing rustup on windows

### ISSUE THREAD

**Issue by BuyMyBeard** [superlistapp/super_native_extensions#387]
I installed the latest version of rustup yesterday on my windows machine. I had no issues running my Flutter app prior to that with my super_native_contextmenu package. Now, it stalls forever on "Installing NDK 23.1.7779620" when I go to run my app. It did run the app after, but I had to wait about 10-15 minutes.

Here is the relevant log with `flutter run --verbose`

[        ] INFO: Precompiled binaries are disabled
[        ] INFO: Installing NDK 23.1.7779620
[+723583 ms] SEVERE: ================================================================================
[  +13 ms] SEVERE: Cargokit BuildTool failed with error:
[        ] SEVERE: --------------------------------------------------------------------------------
[        ] SEVERE: External Command: W:\Android\cmdline-tools\latest\bin\sdkmanager.bat "--install" "ndk;23.1.7779620"
[        ] SEVERE: Returned Exit Code: 1
[        ] SEVERE: --------------------------------------------------------------------------------
[        ] SEVERE: STDOUT:
[        ] SEVERE: Loading package information...
[        ] Loading local repository...
[        ] [                                       ] 3% Loading local repository...        
[        ] [                                       ] 3% Fetch remote repository...
[        ] [=                                      ] 3% Fetch remote repository...
[        ] [=                                      ] 4% Fetch remote repository...
[        ] [=                                      ] 5% Fetch remote repository...
[        ] [==                                     ] 5% Fetch remote repository...
[        ] [==                                     ] 6% Fetch remote repository...
[        ] [==                                     ] 7% Fetch remote repository...
[        ] [==                                     ] 7% Computing updates...
[        ] [===                                    ] 8% Computing updates...
[        ] [===                                    ] 10% Computing updates...
[        ] [===                                    ] 10% Installing NDK (Side by side) 23.1
[        ] [===                                    ] 10% Verifying previous download...    
[        ] [===                                    ] 10% Checking existing file...
[        ] [===                                    ] 10% Downloading android-ndk-r23b-windo
[        ] [====                                   ] 10% Downloading android-ndk-r23b-windo
[        ] [====                                   ] 11% Downloading android-ndk-r23b-windo
[        ] [====                                   ] 12% Downloading android-ndk-r23b-windo
[        ] [=====                                  ] 13% Downloading android-ndk-r23b-windo
[        ] [=====                                  ] 14% Downloading android-ndk-r23b-windo
[        ] [=====                                  ] 15% Downloading android-ndk-r23b-windo
[        ] [======                                 ] 15% Downloading android-ndk-r23b-windo
[        ] [======                                 ] 16% Downloading android-ndk-r23b-windo
[        ] [======                                 ] 17% Downloading android-ndk-r23b-windo
[        ] [=======                                ] 18% Downloading android-ndk-r23b-windo
[        ] [=======                                ] 19% Downloading android-ndk-r23b-windo
[        ] [=======                                ] 20% Downloading android-ndk-r23b-windo
[        ] [========                               ] 20% Downloading android-ndk-r23b-windo
[        ] [========                               ] 21% Downloading android-ndk-r23b-windo
[        ] [========                               ] 22% Downloading android-ndk-r23b-windo
[        ] [=========                              ] 23% Downloading android-ndk-r23b-windo
[        ] [=========                              ] 24% Downloading android-ndk-r23b-windo
[        ] [=========                              ] 25% Downloading android-ndk-r23b-windo
[        ] [==========                             ] 25% Downloading android-ndk-r23b-windo
[        ] [==========                             ] 26% Downloading android-ndk-r23b-windo
[        ] [==========                             ] 27% Downloading android-ndk-r23b-windo
[        ] [===========                            ] 28% Downloading android-ndk-r23b-windo
[        ] [===========                            ] 29% Downloading android-ndk-r23b-windo
[        ] [===========                            ] 30% Downloading android-ndk-r23b-windo
[        ] [============                           ] 30% Downloading android-ndk-r23b-windo
[        ] [============                           ] 31% Downloading android-ndk-r23b-windo
[        ] [============                           ] 32% Downloading android-ndk-r23b-windo
[        ] [============                           ] 33% Downloading android-ndk-r23b-windo
[        ] [============                           ] 33% Downloading android-ndk-r23b-windo
[        ] SEVERE: --------------------------------------------------------------------------------
[        ] SEVERE: STDERR:
[   +2 ms] SEVERE: Warning: Failed to download package!
[   +1 ms] SEVERE: --------------------------------------------------------------------------------
[        ] SEVERE: #0      runCommand (package:build_tool/src/util.dart:118:5)
[        ] SEVERE: #1      AndroidEnvironment.installNdk (package:build_tool/src/android_environment.dart:73:5)
[        ] SEVERE: #2      RustBuilder._buildEnvironment (package:build_tool/src/builder.dart:190:13)
[        ] SEVERE: #3      RustBuilder.build (package:build_tool/src/builder.dart:157:26)
[   +1 ms] SEVERE: #4      ArtifactProvider.getArtifacts (package:build_tool/src/artifacts_provider.dart:68:39)
[   +2 ms] SEVERE: <asynchronous suspension>
[        ] SEVERE: #5      BuildGradle.build (package:build_tool/src/build_gradle.dart:32:23)
[        ] SEVERE: <asynchronous suspension>
[        ] SEVERE: #6      BuildGradleCommand.runBuildCommand (package:build_tool/src/build_tool.dart:62:5)
[        ] SEVERE: <asynchronous suspension>
[        ] SEVERE: #7      BuildCommand.run (package:build_tool/src/build_tool.dart:34:5)
[        ] SEVERE: <asynchronous suspension>
[        ] SEVERE: #8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ] SEVERE: <asynchronous suspension>
[        ] SEVERE: #9      runMain (package:build_tool/src/build_tool.dart:248:5)
[        ] SEVERE: <asynchronous suspension>
[        ] SEVERE: --------------------------------------------------------------------------------
[        ] SEVERE: BuildTool arguments: [build-gradle]
[        ] SEVERE: ================================================================================
[  +45 ms] :irondash_engine_context:cargokitCargoBuildIrondash_engine_context_nativeDebug (Thread[Execution worker Thread 9,5,main]) completed.
Took 12 mins 6.913 secs.

[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3593], locale en-CA)
    • Flutter version 3.22.2 on channel stable at W:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (9 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at W:\Android
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = W:\Android
    • Java binary at: W:\Android\AndroidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34607.119
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at W:\Android\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.90.1)
    • VS Code at C:\Users\alexa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.90.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.3593]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 125.0.6422.176
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 125.0.2535.92

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by BuyMyBeard** [comment]
Found the problem by running the external command manually in a cmd: 
`W:\Android\cmdline-tools\latest\bin\sdkmanager.bat "--install" "ndk;23.1.7779620`
I then found out my JAVA_HOME was set incorrectly and I didn't have my java sdk installed.
The output doesn't say that and simply stalled forever.

**Comment by knopp** [comment]
The ndk installer seems to be running correctly so I don't quite understand how the JAVA_HOME could have been causing this. Also the JAVA_HOME should be set correctly by the flutter_tool.
