### ISSUE TITLE
Wasm compilation fails because of `html` package usage

### ISSUE THREAD

**Issue by sbis04** [superlistapp/super_native_extensions#391]
Compilation for web using Wasm fails because of the usage of `html` package. 

<img width="1186" alt="Screenshot 2024-07-03 at 2 25 51 PM" src="https://github.com/superlistapp/super_native_extensions/assets/43280874/ad7bc4ff-12c7-45ab-8dbd-dfc7b84f465b">

Upgrading to use the `web` package should resolve this issue.

Ref: https://docs.flutter.dev/platform-integration/web/wasm

**Comment by knopp** [comment]
You seem to be using old version. 0.8.17 should build with wasm.

**Comment by sbis04** [comment]
Thanks! Yes, the issue doesn't exist in version `0.8.17`.
