### ISSUE TITLE
Super Drag and Drop Crash when dragging audio file from another app into flutter app

### ISSUE THREAD

**Issue by JerContact** [superlistapp/super_native_extensions#395]
I got this error when dragging a file from one application (specifically an audio editing software) over my app

```
Connecting to VM Service at ws://127.0.0.1:54459/vC3pn_2wPTo=/ws
2024-07-19T22:43:01.212Z ERROR [] Unexpected error Invalid FORMATETC structure (0x80040064) at src\.\win32\drop.rs:488:22
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: FromBytesWithNulError { kind: InteriorNul(86) }', src\.\win32\reader.rs:476:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: Rust panics must be rethrown
Lost connection to device.

Exited.
```

This is on Windows 11

This happened when i used a audio editing software to drag a file out of that software into my app. 

https://github.com/user-attachments/assets/1d8856fa-651a-4ffe-be51-c179e18655f4

**Comment by JerContact** [comment]
Another example of a already existing and rendered file being dragged over the app and crashing

https://github.com/user-attachments/assets/0bc3747d-6ab6-4b52-b1c6-20200a0af701

**Comment by knopp** [comment]
What is the software? It seems to have a rather weirdly implemented the IDataObject it provides during drag. I'd need to reproduce this locally in order to fix it.

**Comment by JerContact** [comment]
Sorry, I thought I responded to this.  The software is Reaper 

https://www.reaper.fm/download.php

You can download it for free as a trial, you'll need to open the "Media Explorer" to drag out a file.  Once you open that you can look at the videos above to see how I crashed super drag and drop

![image](https://github.com/user-attachments/assets/f74a8bd0-8524-4a1d-98bc-7948d2069047)
