### ISSUE TITLE
super_context_menu Title is not a widget

### ISSUE THREAD

**Issue by el2zay** [superlistapp/super_native_extensions#399]
Why is title not a widget but a string? 
It might help to customise the context menu. . Like adding a Row to have more than just an icon and text. Or even a [Dismissible](https://docs.flutter.dev/cookbook/gestures/dismissible) that lets you perform an action like deleting an item from the context menu by dragging.

**Comment by knopp** [comment]
On some platform context menu is using native platform menu, which means it is not possible to use arbitrary widgets.
