### ISSUE TITLE
Compile error on Android

### ISSUE THREAD

**Issue by ErnestDaDev** [superlistapp/super_native_extensions#41]
Hi Guys,
was testing out the super,_clipboard plugin, i ran your example and did all settings, but on android i get this error when compiling

`Compiling build_tool v0.1.0 (C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\super_native_extensions-0.1.8+1\cargokit\build_tool)
    Finished dev [unoptimized + debuginfo] target(s) in 4.09s
     Running `C:\Users\Ernesto\Documents\Custom\debug\build_tool.exe Packages\super_native_extensions\super_clipboard\example\build\super_native_extensions/build/rust_tool -- build_android`
Build tool failed:
Invalid command: Packages\super_native_extensions\super_clipboard\example\build\super_native_extensions/build/rust_tool
error: process didn't exit successfully: `C:\Users\Documents\Custom\debug\build_tool.exe Packages\super_native_extensions\super_clipboard\example\build\super_native_extensions/build/rust_tool -- build_android` (exit code: 1)`

I am not sure what is giving it this error. Can you assist? @knopp

**Comment by knopp** [comment]
I don't think I've ever tested android build on windows. [Cargokit](https://github.com/irondash/cargokit) probably needs some work there.

**Comment by knopp** [comment]
Should be fixed in 0.2.0. Please reopen if the problem persists.

**Comment by davidkalil10** [comment]
I have the same issue here running on windows. Do you already know how to fix it?

**Comment by knopp** [comment]
Do you got the error on 0.2.0? Can you post here the log?
