### ISSUE TITLE
0.8.19 has bug

### ISSUE THREAD

**Issue by cgzcgb** [superlistapp/super_native_extensions#414]
Building Windows application...
  SEVERE: error[E0658]: use of unstable library feature '**cstr_count_bytes**'
SEVERE : error : could not compile `super_native_extensions` (lib) due to 1 previous error [C:\cgz\n_desktop\build\windows\x64\plugins\super_native_extensions\super_native_extensions_plugin_cargokit.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: “C:\cgz\n_desktop\build\windows\x64\CMakeFiles\12c8607d114ee118ee87392f4b679c73\super_native_extensions.dll.rule;C:\cgz\n_desktop\build\windows\x64\CMakeFiles\075bb8925e1cbcc12769fb923e861807\super_native_extensions_plugin_cargokit.rule”的自定义生成已退出，代码为 -1。 [C:\cgz\n_desktop\build\windows\x64\plugins\super_native_extensions\super_native_extensions_plugin_cargokit.vcxproj]
Error: Build process failed.

[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [版本 10.0.19045.4651], locale zh-CN)
    • Flutter version 3.24.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by knopp** [comment]
Can you do `rustup update` and try again?

**Comment by knopp** [comment]
Please reopen if the issue exists after running `rustup update`.

**Comment by cgzcgb** [comment]
This problem still exists.

**Comment by knopp** [comment]
Can you please post output of `rustc --version` and verbose flutter build log?

**Comment by cgzcgb** [comment]
rustc 1.78.0 (9b00956e5 2024-04-29)

**Comment by knopp** [comment]
Latest stable version is ` 1.80.1`. It should have been updated after `rustup update`.

**Comment by cgzcgb** [comment]
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
Thank you very much. It's okay after upgrading to the latest version
