### ISSUE TITLE
Bump web to 1.0

### ISSUE THREAD

**Issue by CodeDoctorDE** [superlistapp/super_native_extensions#415]
Hi, I want to use the new web 1.0 library. Can you bump the web library in super_native_extensions?

**Comment by lindsaycharlotte2023** [comment]
https://github.com/CodeDepot-Hub/super_native_extensions/tree/1.0/1.0.0  web 1.0.0

**Comment by knopp** [comment]
Why not make a pull request for this?

**Comment by CodeDoctorDE** [comment]
thanks for updating
