### ISSUE TITLE
[macOS] NSWindow is not movable after resizing

### ISSUE THREAD

**Issue by leonx98** [superlistapp/super_native_extensions#42]
Hey Matej,

we use the NSWindow method `isMovable` to be able to move our application by its titlebar. Since we have been using your plugin (super_drag_and_drop), this no longer works after resizing the window.

**Comment by knopp** [comment]
Can you be more specific? I tried setting 
```swift
    self.isMovable = true
    self.isMovableByWindowBackground = true
```
for `NSWindow` and it didn't work in "vanilla" Flutter application either. Which is expected because the FlutterView handles mouse events. 

In general for dragging at arbitrary location we're using `NSWindow performWindowDragWithEvent:`, but that's quite a bit involved and currently only implemented in NativeShell. I might consider bringing some version of this into `super_native_extensions`.

**Comment by leonx98** [comment]
Hmm... strange, but it works for us. In the `awakeFromNib()` method we set `isMovable = true` and dragging using the titlebar is possible. Only after a resize (maximize window and back) does this no longer work. Without your plugin everything works fine 🤔

**Comment by knopp** [comment]
Sorry, I misread, I thought you wanted to implement dragging using window contents. Window should be draggable by titlebar by default. You shouldn't be needing to set isMovable in `awakeFromNib`.

Are you able to reproduce this with drag & drop example? Are you able to drag it after resize?

**Comment by leonx98** [comment]
Yes, it's a standard behavior with the normal title bar.
I was able to reproduce the behavior in the example project as well. We use a transparent title bar (in the .xib file turn on `Transparent Title Bar` and `Full Size Content View`).
The window can no longer be moved after it has been resized (resize by dragging the edge or zooming), although `isMovable` is true.

**Comment by knopp** [comment]
I can reproduce this with combination of transparent title bar + full size content view. I'm looking into it.

**Comment by knopp** [comment]
Can you retry this with super_drag_and_drop 0.1.9+3 and if the problem persists reopen the issue?

**Comment by leonx98** [comment]
It works now. Wonderful, thank you! 🚀
