### ISSUE TITLE
URGENT: Drag and Drop (OnDrop Region) doesn't work on Android

### ISSUE THREAD

**Issue by TheArchitect123** [superlistapp/super_native_extensions#433]
When dragging DragableItems into **DropRegion** onPerformDrop fails.
**I get the below error.**

E/flutter (11953): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(super_native_extensions_error, invalid engine handle, engineContextError, null)
E/flutter (11953): #0 NativeMethodChannel.invokeMethod (package:irondash_message_channel/src/method_channel.dart:45:7)
E/flutter (11953):
E/flutter (11953): https://github.com/superlistapp/super_native_extensions/pull/1 DragContextImpl.startDrag (package:super_native_extensions/src/native/drag.dart:241:9)
E/flutter (11953):
E/flutter (11953): https://github.com/superlistapp/super_native_extensions/pull/2 LongPressSession.extend (package:super_native_extensions/src/drag_interaction/long_press_session.dart:35:14)
E/flutter (11953):
E/flutter (11953):

**I got this error ever since upgrading to the latest Flutter SDK (v3.24.3).
I also can't rollback anymore to a previous version, because it will cause issues on my current project.**

**Comment by knopp** [comment]
That looks like the dylib did not get loaded. You might get an error message with the reason during application startup in adb logcat.

**Comment by TheArchitect123** [comment]
I'll post the logs from logcat

**Comment by TheArchitect123** [comment]
**Here are my logcat logs. I've attached these into a text file because the text is too large to paste here.** 
[SuperDragAndDropLogCatLogs.txt](https://github.com/user-attachments/files/17043167/SuperDragAndDropLogCatLogs.txt)

**Comment by TheArchitect123** [comment]
**Here are the logs that come up on AppStartup**

[SuperDragAndDropLogCatLogsOnAppStartup.txt](https://github.com/user-attachments/files/17043233/SuperDragAndDropLogCatLogsOnAppStartup.txt)

**Comment by TheArchitect123** [comment]
> **Here are my logcat logs. I've attached these into a text file because the text is too large to paste here.** [SuperDragAndDropLogCatLogs.txt](https://github.com/user-attachments/files/17043167/SuperDragAndDropLogCatLogs.txt)
> 
> @knopp

These logs are scoped to when I drag and drop items onto the DropRegion

**Comment by TheArchitect123** [comment]
Hi @knopp 

Have you managed to take a look at the logcat logs?
Do you see any reason why this would fail. I couldn't find any initialisation issues on AppStartupLogs.

Thanks,

**Comment by TheArchitect123** [comment]
I found it's a configuration problem with my project.
I tried the example project and it works fine

**Comment by TheArchitect123** [comment]
@knopp 
Turns out the issue was because I was using a **FlutterFragmentActivity** instead of a **FlutterActivity**.
**FlutterFragmentActivity** I needed because of Biometric Services. I'll have to find a workaround for that for now.

**Comment by thaidmfinnick** [comment]
@TheArchitect123 do you find a workaround, I meet the same case with you :D

**Comment by ganwumeng** [comment]
Solved. Change the code in IrondashEngineContextPlugin.java.

Original:
```java
  static public View getFlutterView(long handle) {
    final Activity activity = getActivity(handle);
    if (activity != null) {
      return activity.findViewById(FlutterActivity.FLUTTER_VIEW_ID);
    } else {
      return null;
    }
  }
```

After:
```java
  private static FlutterView findFlutterViewRecursive(View view) {
    if (view instanceof FlutterView) {
      return (FlutterView) view;
    }
    
    if (view instanceof ViewGroup) {
      ViewGroup viewGroup = (ViewGroup) view;
      for (int i = 0; i < viewGroup.getChildCount(); i++) {
        View child = viewGroup.getChildAt(i);
        FlutterView result = findFlutterViewRecursive(child);
        if (result != null) {
          return result;
        }
      }
    }
    
    return null;
  }

  static public View getFlutterView(long handle) {
    final Activity activity = getActivity(handle);
    if (activity == null) {
      return null;
    }
    
    View flutterView = activity.findViewById(FlutterActivity.FLUTTER_VIEW_ID);
    if (flutterView != null) {
      return flutterView;
    }
    
    View decorView = activity.getWindow().getDecorView();
    return findFlutterViewRecursive(decorView.getRootView());
  }
```
