### ISSUE TITLE
【super_clipboard 】does not support win7 ?

### ISSUE THREAD

**Issue by zhouzhuo810** [superlistapp/super_native_extensions#439]
The question is rustup cannot run on win7.

so super_clipboard cannot run on win7.

any way to run on win7?

**Comment by zhouzhuo810** [comment]
![image](https://github.com/user-attachments/assets/0c6cb932-b514-4eaf-a5e8-9c593b0ace71)

**Comment by zhouzhuo810** [comment]
help ! help ! help ! please.

**Comment by knopp** [comment]
Sorry, there is no intention for supporting Windows 7. Rust dropped support for Windows 7 in 2023, and IIRC Flutter has also dropped support for Windows 7 recently.
