### ISSUE TITLE
Windows not building

### ISSUE THREAD

**Issue by Coinners** [superlistapp/super_native_extensions#446]
```
Launching lib\main.dart on Windows in debug mode...
CMake Error at flutter/generated_plugins.cmake:16 (add_subdirectory):
  add_subdirectory given source
  "flutter/ephemeral/.plugin_symlinks/irondash_engine_context/windows" which
  is not an existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:58 (include)
2

CMake Error at flutter/generated_plugins.cmake:16 (add_subdirectory):
  add_subdirectory given source
  "flutter/ephemeral/.plugin_symlinks/super_native_extensions/windows" which
  is not an existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:58 (include)
2

Error: Unable to generate build files

Exited (1).
```

I encounter the following error even after running `flutter clean`, recreating the windows build files and removing and readding the plugin from pub

**Comment by knopp** [comment]
This seems like the symlinks are not sent properly by flutter tool? There definitly is `windows` directory in both `irondash_engine_context` and `super_native_extensions` plugin.

**Comment by Coinners** [comment]
Hmm
I investigated further and it looks like it was a windows issue
I also noticed that flutter commands stopped working eventhough it was still added to my PATH
