### ISSUE TITLE
[Windows] Error when pasting image to clipboard

### ISSUE THREAD

**Issue by zap-janitor** [superlistapp/super_native_extensions#50]
```
"Windows Error: CoInitialize has not been called. (0x800401F0)"
```

**Comment by knopp** [comment]
Do you call `OleInitialize()` at the beginning on your main function?

**Comment by knopp** [comment]
Also, are you able to reproduce this with the example?

**Comment by djpnewton** [comment]
no I did not see the change to main.cpp.

I also see that https://github.com/superlistapp/super_native_extensions/pull/51 will remove this issue. Will you make a new release?

**Comment by knopp** [comment]
0.2.0 has been released. OleOnitialize should be called by the plugin now.
