### ISSUE TITLE
[super_drag_and_drop] drag and drop plain text to flutter web failed

### ISSUE THREAD

**Issue by charlestp** [superlistapp/super_native_extensions#65]
Hi. Thanks for the great package.

I am using `super_drag_and_drop` and I have encountered an issue when dragging text to a flutter web application (Chrome).
It is working in the macOS version.

The assertion in `super_native_extensions/lib/src/web/drop.dart` failed since the file is null.

```
@override
Future<VirtualFileReceiver?> createVirtualFileReceiver(
  DataReaderItemHandle handle, {
  required String format,
}) async {
  assert(file != null,
      'Should not have requested virtual file receiver without file');
  return _VirtualFileReceiver(format, file!);
}
```

I removed the assertion and changed it to `return file == null ? null : _VirtualFileReceiver(format, file!);` and it works

To reproduce:

Simply drag an drop text from chrome or excel to a flutter web app.

flutter version: 3.7.0
super_drag_and_drop: 0.2.0
chrome: 110.0.5481.77

**Comment by knopp** [comment]
Please reopen if you still have this problem with 0.2.1.
