### ISSUE TITLE
Failed to execute 'write' on 'Clipboard'  on Flutter web

### ISSUE THREAD

**Issue by rodrigo-badaro** [superlistapp/super_native_extensions#71]
I'm using this package to copy a table with information to be pasted in e-mail body and when I run locally its works fine, but when I deploy to firebase hosting I get this error. I try with Chrome and Edge

`TypeError: Failed to execute 'write' on 'Clipboard': The object must have a callable @@iterator property.`

**Comment by knopp** [comment]
It fails in release mode. Should be fixed in next update.
