### ISSUE TITLE
[macos][super_drag_and_drop] cant read file from outlook

### ISSUE THREAD

**Issue by socramm9** [superlistapp/super_native_extensions#79]
Files from Desktop can be readed using:

```
onPerformDrop: (event) async {
        final item = event.session.items.first;

        // data reader is available now
        final reader = item.dataReader!;

        if (reader.canProvide(Formats.fileUri)) {
          reader.getValue<Uri>(
            Formats.fileUri,
            (value) async {
              if (value != null) {
                // You can access values through the `value` property.
                print('Dropped text: $value');
                print(value.toFilePath());
              }
            },
            onError: (error) {
              print('Error reading value $error');
            },
          );
        }
},
```

But for Files Dragged from Outlook (Desktop client) it does not support `Formats.fileUri` format

On Windows it works fine in booth cases. What am I doing wrong?

**Comment by knopp** [comment]
It is possible that outlook uses file promises (aka virtual files) in which case there is no URL and you will need to read file content instead through `getFile(format)`.

**Comment by knopp** [comment]
I just tested this and it seems that the file promise metadata outlook uses is different than what standard `NSFilePromiseProvider` produces. I'll post update soon.

**Comment by knopp** [comment]
Can you try this with `super_drag_and_drop` `0.2.3+1`? 
`Formats.pdf` should work for PDF file.

**Comment by socramm9** [comment]
I think it works now. I am not done testing yet. Tanks allot for your fast Support. 

One more thing not sure if is an issue or I am doing it wrong. But I have to pass the `FileFormat` to the `getFile` method. But for that I would need to know the format from reader. This is what I tried:
<img width="597" alt="Bildschirm­foto 2023-03-14 um 16 35 37" src="https://user-images.githubusercontent.com/52098754/225054695-0d9aa295-fb5c-47fe-9170-4b803d2595c6.png">

It gets the correct format but the return type is not supported by `getFile`

<img width="684" alt="Bildschirm­foto 2023-03-14 um 16 38 53" src="https://user-images.githubusercontent.com/52098754/225055016-d4971d27-783a-4084-8d85-434d9f889988.png">
<img width="984" alt="Bildschirm­foto 2023-03-14 um 16 35 51" src="https://user-images.githubusercontent.com/52098754/225055054-dab01053-0392-4d8f-b118-4960d8176932.png">

**Comment by knopp** [comment]
In this case you will need to check if the format is `FileFormat` and then cast it to `FileFormat`.

```dart
if (format is FileFormat) {
   final fileFormat= format as FileFormat;
}
```

**Comment by socramm9** [comment]
Okay got it know the issue was also that I had to import FileFormat from super_clipboard

**Comment by knopp** [comment]
> Okay got it know the issue was also that I had to import FileFormat from super_clipboard

That seems like a oversight. `FileFormat` should be reexported by `super_drag_and_drop`. I'll look into that.

**Comment by knopp** [comment]
You can create the `Format` definitions that you're missing. If you give me a list of formats that you are missing I can add them to `super_native_extensions`. I'd like the default list to be as comprehensive as possible.

Btw. yaml on other platforms will be reported as `text/x-yaml` (even though that's a deprecated definition).

**Comment by socramm9** [comment]
> Btw. yaml on other platforms will be reported as text/x-yaml (even though that's a deprecated definition).

Strange I don't get anything from yaml files. But it works fine if I add my own definition;

> If you give me a list of formats that you are missing I can add them to super_native_extensions.

You could add Types for all types of code files: .dart, .ts, .js, .dart, ...


But If possible I would need a more generic approach. I have to support all types of files no matter what. :(

I also had issue whit .html files it was not returning `FileFormat` but `ValueFormat` so I tried using `getValue`, but the value returned from callback was null

**Comment by knopp** [comment]
Right. We're likely missing a `FileFormat` for `public.html`. The value format is meant for copying and pasting rich text, which is treated as value (and needs additional conversion of some platforms).

As for generic access - you should be able to use `DataReader.platformFormats` to get all available formats and then construct `SimpleFileFormat(fallbackFormats:[firstPlatformFormat]`).

This might be a common enough use case to just support it out of box. You can try something like this (I haven't tested the code):

```dart
extension on DataReader {
  raw.ReadProgress? getAnyFile(
    AsyncValueChanged<DataReaderFile> onFile, {
    ValueChanged<Object>? onError,
  }) {
    final formats = platformFormats;
    if (formats.isNotEmpty) {
      final format = formats.first;
      return getFile(
        SimpleFileFormat(fallbackFormats: [format]),
        onFile,
        onError: onError,
      );
    } else {
      return null;
    }
  }
}
```

**Comment by socramm9** [comment]
Yes it works thanks allot!
